# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, base64
from urllib.parse import urlencode

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "Your Token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = "http://username:password@ip:port"

def run_task(payload):
    # Task JSON payload
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return
        
def riskbypass_tls_forward(url, methods, headers, data, cookies, proxy, timeout=30):
    if type(data) == str:
        body_base64 = base64.b64encode(data.encode()).decode()
    elif type(data) == bytes:
        body_base64 = base64.b64encode(data).decode()
    elif type(data) == dict:
        network_data = urlencode(data)
        body_base64 = base64.b64encode(network_data.encode()).decode()
    else:
        body_base64 = None
    payload = {
        "task_type": "tls_forward",
        "proxy": proxy,
        "url": url,
        "method": methods,
        "headers": headers,
        "body_base64": body_base64,
        "cookies_dict": cookies,
        "timeout": timeout
    }
    result = run_task(payload)
    if not result:
        raise Exception("Tls Forward failed.")
    else:
        return RiskbypassResponse(result)

class RiskbypassResponse:
    def __init__(self, response_dict):
        self.body = base64.b64encode(response_dict.get('body_base64').encode())
        self.cookies = response_dict.get('cookies', {})
        self.elapsed = response_dict.get('elapsed', 0)
        self.error = response_dict.get('error', None)
        self.headers = response_dict.get('headers', {})
        self.ok = response_dict.get('ok', False)
        self.reason = response_dict.get('reason', '')
        self.status_code = response_dict.get('status_code', 0)
        self.text = response_dict.get('text', '')
        self.url = response_dict.get('url', '')
    
    def json(self):
        return json.loads(self.body)


if __name__ == "__main__":
    akamai_payload = {
        "task_type": "akamai",
        "proxy": PROXY,
        "target_url": "https://catering.panerabread.com/",
        "akamai_js_url": "https://catering.panerabread.com/wq7Hm6aSruxwjxF_DQ/f7wi8SrQGfLhmr/FxwfRw/NWQwC/WNvd24B",
        "page_fp": "42455e5a4e485c515f5e43455e5a4e494b"
    }
    akamai_result = run_task(akamai_payload)
    if not akamai_result:
        raise Exception("Task failed.")
    cookies = akamai_result.get('cookies_dict')

    headers = {
        'accept': 'application/json, text/plain, */*',
        'accept-language': 'zh-CN,zh;q=0.9',
        'cache-control': 'no-cache',
        'cater-cloud-services': '',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://catering.panerabread.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://catering.panerabread.com/',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
        'x-business-unit': 'cater',
        'x-kount-session': 'd22011eff1ab4397b0b4ecf0b1dd6108',
        'x-locale': 'en-US',
    }

    data = {
        'grant_type': 'password',
        'username': 'sadfsdf',
        'password': 'sadfsdafsda',
    }

    response = riskbypass_tls_forward(
        url='https://catering.panerabread.com/foundation-api/public/auth',
        methods='POST',
        cookies=cookies,
        headers=headers,
        data=data,
        proxy=PROXY
    )
    print(response.text)
    print(response.status_code)