# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
from riskbypass import RiskByPassClient
import requests_go
import re

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 120                         # Max task execution time (seconds), exceeding this will throw an exception
PROXY = f"http://username:password@host:port" # your proxy

client = RiskByPassClient(token=TOKEN, dev_id='dev_5FZQrruzoeUyHD1E')

tls_config = requests_go.tls_config.TLS_CHROME_LATEST

headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-language': 'en,en-US;q=0.9,zh-CN;q=0.8,zh;q=0.7',
    'cache-control': 'no-cache',
    'pragma': 'no-cache',
    'priority': 'u=0, i',
    'sec-ch-ua': '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
}

response = requests_go.get('https://www.dana.id/games/activities', headers=headers, proxies={'https':PROXY}, tls_config=tls_config)
init_cookies = response.cookies.get_dict()
print(init_cookies)
payload = {
  "task_type": "akamai",
  "proxy": "http://username:password@ip:port",
  "target_url": "https://www.dana.id/games/activities",
  "akamai_js_url": "https://www.dana.id/8IDCJD/zb/KQ/wcPf/e7IoxO3e9XF-I/ht1mmQSXNuSfDL/eVAlAg/MXcM/WTQld10B",
  "page_fp": ""
}
payload['proxy'] = PROXY
payload['akamai_js_url'] = "https://www.dana.id" + re.findall(r'<script type="text/javascript"  src="(.*?)">', response.text)[0]
result = client.run_task(payload)

init_cookies.update(result['cookies_dict'])

headers = {
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9,id',
    'baggage': 'sentry-environment=production,sentry-release=dana-game%401.36.0,sentry-public_key=b0fef77f1bacc5dbe45bcefe72e818c2,sentry-trace_id=b876224814234a388b4981af4cb4dbb7,sentry-org_id=370407,sentry-sampled=false,sentry-sample_rand=0.6697232201258635,sentry-sample_rate=0.00065',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    'origin': 'https://www.dana.id',
    'pragma': 'no-cache',
    'priority': 'u=1, i',
    'referer': 'https://www.dana.id/games/activities',
    'sec-ch-ua': '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'sentry-trace': 'b876224814234a388b4981af4cb4dbb7-b3706826193a2b53-0',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
    'x-apdid-token': '019d3237-1bec-7bf9-b66b-8b0fe3835a52',
    'x-fe-request-id': '',
    'x-fe-version': '1.36.0',
    'x-game': 'true',
}

json_data = {
    'transactionQueryType': 'COMPLETED',
    'pageNum': 1,
    'bizOrderType': [
        'ACQUIRING',
        'ACQUIRING_GROUP',
        'REFUND',
        'REFUND_GROUP',
    ],
    'categoryTypes': [
        'GAME',
        'GAME_VOUCHER',
        'GAME_ASSET',
        'EGIFTCARD',
        'DIGITAL_VOUCHER',
    ],
}

response = requests_go.post(
    'https://www.dana.id/wallet/api/id.dana.thengine.user.transaction.list.lite.json',
    cookies=init_cookies,
    headers=headers,
    json=json_data,
    proxies={'https':PROXY},
    tls_config=tls_config
)
print(response.text)