# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY    = "http://username:password@host:port" # Proxy URL (optional)

def run_task():
    # Task JSON payload
    payload = {
        "task_type": "akamai",
        "proxy": PROXY,
        "target_url": "https://www.dana.id/games/home",
        "akamai_js_url": "https://www.dana.id/Ed_nrH/57qS/vEz/jEB/wTtbczlfXUU/rhkaGQkND5zkLpY7i3/bAx0YT95BQ/WHlMUDF/6Tjc",
        "page_fp": "42455e5a4e495c515f5e43455e5a4e494b"
    }
    
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    results = run_task()

    cookies = {
        'JSESSIONID': 'GZ00A497B17516984EBD930B69B90626BDB8aphomeGZ00',
        'AKA_A2': 'A',
        '_ga': 'GA1.1.48464611.1765983075',
        'apdid_data': '%7B%22time%22%3A1765983077067%2C%22token%22%3A%22APDIDJS_indonesia_f8cd96a86578d1139ee1112890987f58%22%7D',
        'alipay_apdid_token': '1EUTw8M%2Fiexu9CqtSDnexPZpKJ7woLBXYFX1Lwod%2BlHXJS947LvgxMeodL9mis8J',
        'oneDayId': '2530459301',
        'ALIPAYJSESSIONID': 'GZ00A497B17516984EBD930B69B90626BDB8aphomeGZ00',
        'ctoken': 'znY59lkjxg5gvOt_',
        '_ga_LR31Y7P14Z': 'GS2.1.s1765983075$o1$g1$t1765983235$j60$l0$h0',
        'RT': '"z=1&dm=www.dana.id&si=c12c7c37-64b8-4620-9a47-31f249cf4747&ss=mja4q1o3&sl=1&tt=5ep&rl=1"',
        'mp_ded2d68965bbd813d33d686ee165bae7_mixpanel': '%7B%22distinct_id%22%3A%22%24device%3Aee585234-b64d-4ff0-bdb3-e573906498e2%22%2C%22%24device_id%22%3A%22ee585234-b64d-4ff0-bdb3-e573906498e2%22%2C%22%24initial_referrer%22%3A%22%24direct%22%2C%22%24initial_referring_domain%22%3A%22%24direct%22%2C%22%24search_engine%22%3A%22google%22%2C%22__mps%22%3A%7B%7D%2C%22__mpso%22%3A%7B%22%24initial_referrer%22%3A%22%24direct%22%2C%22%24initial_referring_domain%22%3A%22%24direct%22%7D%2C%22__mpus%22%3A%7B%7D%2C%22__mpa%22%3A%7B%7D%2C%22__mpu%22%3A%7B%7D%2C%22__mpr%22%3A%5B%5D%2C%22__mpap%22%3A%5B%5D%2C%22Solution%22%3A%22Guest%20Checkout%22%7D',
    }
    cookies.update(results['cookies_dict'])

    # get it from captcha.htm's response
    biz = "9ab7d2ed_347e_46a6_83d9_9408664bacf8"
    antCaptchaToken = "0216e7c514ab496285cf2fa0b9d4d9c2f83abfa3e22d4d568acebc17bbe3f613"

    headers = {
        'accept': '*/*',
        'accept-language': 'en-US,en;q=0.9,id',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'origin': 'https://www.dana.id',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.dana.id/n/ipg/new/inputphone?phoneNumber=&ipgForwardUrl=%2Fn%2Fgames%2Fdetail%2Fvoucher%2Fgoogleplay&isFromItemDigital=true',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
        'x-apdid-token': '019b2ccd-aca9-78bd-b59c-3affaa345409',
        'x-client-callback-version': '2.1',
        'x-fe-request-id': '0000000017659832367380002',
        'x-fe-version': '2.41.0',
        'x-nonce': '',
        'x-rds': '196YlF/THlNekF7SnpLf0VyQxw=|YVF/JgZHLV0wXzgYNhYlEyICLAxZMl44VSBRcS5x|YFF/JhQ6CCYVIhIhDzoLORckEyIWOAI2AC4dKhsvATsIPGM8|Z1RnSRAwWixaKFlhTGEUYRQ4Xj1RMh51Ez5SfxRmAy5CJVB9FnoIfwl7EXwQd0o4Uj9TNHgPYABnFygMZxVwNFkpXD9PKX4OYF94SH9PC2dAcEd3M1Y1Wj1Ma1tsXBh+GW8MZwkuHikZXSlEM1I4Xy8IOA8vASFLPUs5SHBdcAVwBSlPLEAjD2QCL0NuC2gHYBE8Wj1LKEMtAHQZbg9lAnJfOlc6XzFWJEopUnItcg==|ZlVlSydQPlAP|ZV9xUTdUOFsGdhF0KVg/SRtuCFVlV2RfbV5uXW1cb1ppXwI0AzIHPR1C|ZFJ8JQUlCzgKPQknECcWOAsxBzNsMw==|a11zKgoqBDcFNAYoHysQPgg7DztkOw==|alxyKwsrBTYFNAQqHy0bNQIwAjdoNw==|aV9xKAgoBjUBMx0rGysFNQ85AjRrNA==|aF1zKgoqBDcZKRMpGCJ9Ig==|b1h2Lw8vAVhrXW9Bd0ByLQMxHz8fMQE7ATcEWwQ=|bl1qRGQ0Uh17AzEEdAxFF1kXLWokF3wzDCxz|bV5pR2c3UR54ADIHdw9GFFoULmEzAGskGztk|bF9oRmY2UB95ATMGdg5HFVsVL2QvHXY5BiZ5|c0B3WXkpTwBmHiwZaRFYCkQKMFEdL0QLNBRL|ckF2WHgoTgFnHy0YaBBZC0ULMWogEGskGztk|cUJ1W3srTQJkHC4baxNaCEYIeTJ7SCNsU3Ms|cEN0WnoqTANlHS8aahJbCUcJaCdrWTJ9QmI9|d0RzXX0tSwRiGigdbRVcDkAObyRuXiVqVXUq|dkVyXHwsSgVjGykcbBRdD0EPbj10RyxjXHwj|dUZxX38vSQZgGCofbxdeDEIMbTZ5STJ9QmI9|dEJsNRU1Gy4aIA4/CD0TIhMlESB/IA==|e0xiOxs7FUx2Q3ZYaVhtMhwuACAALh8oHCgSTRI=|ek9hOBg4FiULOg05DTdoNw==|eU5gORk5F057QXpUZVVvMB4sAiICLB0pEyUUSxQ=|eE5gORk5Fy0eJQs6CzkXJhMlHy9wLw==|f0tlPBw8EiEbNQcpGCMQJxBPEA==|fkhmPx8/ESsdKgQzAzEfJRMnEiB/IA==|fUpkPR09E0p/RHBeb1xpNhgqBCQEKhAnECMZRhk=|fEpkPR09EyYTIgw9DT0TKR0uFS9wLw==|Q3RaAyMDLXRBdUZoWWlZBigaNBQ0GiAUIxMmeSY=|QnVbAiICLHVAdkxiU2NUCyUXORk5Fy0YKR8qdSo=|QXZYASEBL3ZDdU9hUGBXCCYUOho6FC4bLBgucS4=|QHdZACAALndCdE5gUWFWCScVOxs7FS8aIBIgfyA=|R3BeBycHKXBKeUtlVGVTDCIQPh4+ECoQJxUvcC8=|RnFfBiYGKHFLeEpkVWRSDSMRPx8/ESsRJBQifSI=|RXNdBCQEKhkqHyQKMAM1GyEaIBsucS4=|RHJcBSUFKxEjEjwNNwQqGSoaLRYifSI=|S35QCSkJJxQ6CTkJMgk+YT4=|Sn5QCSkJJxQhDz0TIBAhESUVShU=|SX1TCioKJB4qBDcZKhorGiseQR4=|SH1TCioKJBc5CjoNPww3aDc=|T3xSY014VmVWbEJxR3VbbFd5SnhWbUN5V2JMfUZoW21Dc0BxX29cbEJyQXJcbF9tQ3NBelRkVmxCckB1W2tZbUNzQXZYaFpsQm1Zd0dpWW5AclxzQHJcZ0lmVWVLZFJ8U2BWeFdjTWJXeVZsQm1WeFdkVnhXZFd5VmZVe1RkVHpJe1V6TGJNelRhPg==',
    }

    json_data = {
        'phoneNumber': '62-82152343270',
        'extParams': {
            'clientId': '',
            'subMerchantId': '',
            'rdsStandalone': f'{{"bizNo":"{biz}","antCaptchaToken":"{antCaptchaToken}","rdsScene":"nextCheckRegister"}}',
        },
        'skipSendOtp': True,
        'extendInfo': {
            'isSupportWAOtp': True,
        },
    }
    from primp import Client
    client = Client(proxy=PROXY, impersonate='chrome_133')
    response = client.post(
        'https://www.dana.id/wallet/api/alipayplus.mobilewallet.user.checkRegisteredUserAndSendOTP.json',
        cookies=cookies,
        headers=headers,
        json=json_data,
    )
    print(response.text)
