from primp import Client

# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "Your Token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)

PROXY = "http://username:password@host:port"

def run_task():
    payload = {
        "task_type": "akamai",
        "proxy": PROXY,
        "target_url": "https://www.fedex.com/fr-fr/home.html",
        "akamai_js_url": "https://www.fedex.com/q4FlYf8Wq/jryUPMIq/g/9XuELwurwiQ54GzOiY/PCRj/CRUfPjlG/IQE",
        "page_fp": "42455e5a4e495c505f4147514b47534d46595f4349595f465355404d435f435d4a534e54414d434842455e5a4e495c505f4147514b47534d46595f4349595f465355404d425f405c45584e54414d4348"
    }
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    results = run_task()

    cookies = results['cookies_dict']

    headers = {
        'accept': 'application/json',
        'accept-language': 'en',
        'authorization': 'Bearer l7b8ada987a4544ff7a839c8e1f6548eea',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'origin': 'https://www.fedex.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.fedex.com/wtrk/track/?action=track&tracknumbers=213213&locale=fr_FR&cntry_code=us',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
        'x-clientid': 'WTRK',
        'x-locale': 'fr_FR',
        'x-requested-with': 'XMLHttpRequest',
        'x-version': '1.0.0',
    }

    json_data = {
        'appDeviceType': 'WTRK',
        'appType': 'WTRK',
        'supportHTML': True,
        'supportCurrentLocation': True,
        'trackingInfo': [
            {
                'trackNumberInfo': {
                    'trackingCarrier': '',
                    'trackingNumber': '213213',
                    'trackingQualifier': '',
                },
            },
        ],
        'uniqueKey': '',
        'guestAuthenticationToken': '',
    }
    tls_requests = Client(proxy=PROXY, impersonate='chrome_133')
    response = tls_requests.post('https://api.fedex.com/track/v2/shipments', cookies=cookies, headers=headers, json=json_data)
    print(response.text)
