# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json
from curl_cffi import requests as c_requests

BASE_URL = "https://riskbypass.com"                     # API base URL
TOKEN    = "Your Token"                                 # Access token (sent as x-api-key)
TIMEOUT  = 60                                           # Timeout (seconds)
PROXY    = "http://username:password@host:port"         # Proxy string

def get_ct():
    # Task JSON payload
    payload = {
        "task_type": "kasada",
        "proxy": PROXY,
        "target_url": "https://arcteryx.com/ca/en/shop/mens/rush-bib-pant-9904",
        "protected_api_domain": "arcteryx.com",
        "kasada_js_domain": "arcteryx.com"
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

def get_cd(ct, st, fc, site='arcteryx'):
    # Task JSON payload
    payload = {
        "task_type": "kasada_cd",
        "ct": ct,
        "st": st,
        "fc": fc,
        "site": site
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    # kasada-cd api is free if you contact us
    kasada_args = get_ct()
    ct = kasada_args['x-kpsdk-ct'] # Get the x-kpsdk-ct
    st = kasada_args['x-kpsdk-st'] # Get the x-kpsdk-st
    v = kasada_args['x-kpsdk-v'] # Get the x-kpsdk-v
    h = kasada_args['x-kpsdk-h'] # Get the x-kpsdk-h
    fc = kasada_args['x-kpsdk-fc'] # Get the x-kpsdk-fc
    cd = get_cd(ct=ct, st=st, fc=fc) # Get the x-kpsdk-cd
    user_agent = kasada_args['user-agent'] # Get the user-agent
    sec_ch_ua = kasada_args['sec-ch-ua'] # Get the sec-ch-ua
    sec_ch_ua_platform = kasada_args['sec-ch-ua-platform'] # Get the sec-ch-ua-platform

    headers = {
        'x-kpsdk-ct': ct,
        'sec-ch-ua-platform': sec_ch_ua_platform,
        'authorization': 'Bearer',
        'Referer': 'https://arcteryx.com/ca/en/shop/mens/rush-bib-pant-9904',
        'x-kpsdk-h': h,
        'sec-ch-ua': sec_ch_ua,
        'newrelic': 'eyJ2IjpbMCwxXSwiZCI6eyJ0eSI6IkJyb3dzZXIiLCJhYyI6IjI0Nzg0NzAiLCJhcCI6IjM2NzQ5MTg0OCIsImlkIjoiN2Q5ZjEzY2FhYmFhNmQxOCIsInRyIjoiZjU1NmI3YjlhMjQ0YmM5ZDZiOTZlMzNkODM2ZTdjNzYiLCJ0aSI6MTc2NDIzMjgzMDM1Mn19',
        'sec-ch-ua-mobile': '?0',
        'traceparent': '00-f556b7b9a244bc9d6b96e33d836e7c76-7d9f13caabaa6d18-01',
        'x-kpsdk-v': v,
        'x-kpsdk-cd': cd,
        'User-Agent': user_agent,
        'x-kasada-access-token': '',
        'content-type': 'application/json',
        'tracestate': '2478470@nr=0-1-2478470-367491848-7d9f13caabaa6d18----1764232830352',
    }

    json_data = {
        'json': {
            'country': 'ca',
            'language': 'en',
            'modelSku': 'X000009904',
            'variantSku': 'X000009904005',
            'quantity': 1,
            'cartId': 'L4QbPprG9wrFwnYiViRhbTJDVESWZYS5',
        },
    }

    for i in range(10):
        print(f'Request {i+1} times')
        response = c_requests.post(
                    url='https://arcteryx.com/api/cart.addItem',
                    headers=headers,
                    json=json_data,
                    proxies={'http': PROXY, 'https': PROXY},
                    impersonate='firefox135'
                )
        print(response.text)
        print(response.status_code)
        next_ct = dict(response.cookies).get('KP_UIDz')
        if next_ct:
            ct = headers['x-kpsdk-ct'] = next_ct
        headers['x-kpsdk-cd'] = get_cd(ct=ct, st=st, fc=fc)