# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, random

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = "http://username:password@host:port"

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    ct_payload = {
        "task_type": "kasada",
        "proxy": PROXY,
        "target_url": "https://www.footlocker.com/giftcards/checkbalance.html",
        "protected_api_domain": "www.footlocker.com",
        "kasada_js_domain": "www.footlocker.com"
    }
    ct_result = run_task(ct_payload)
    if not ct_result:
        raise Exception("Failed to get ct_result")

    ct = ct_result['x-kpsdk-ct'] # Get the x-kpsdk-ct
    st = ct_result['x-kpsdk-st'] # Get the x-kpsdk-st
    v = ct_result['x-kpsdk-v'] # Get the x-kpsdk-v
    h = ct_result['x-kpsdk-h'] # Get the x-kpsdk-h
    fc = ct_result['x-kpsdk-fc'] # Get the x-kpsdk-fc
    user_agent = ct_result['user-agent'] # Get the user-agent
    sec_ch_ua = ct_result['sec-ch-ua'] # Get the sec-ch-ua
    sec_ch_ua_platform = ct_result['sec-ch-ua-platform'] # Get the sec-ch-ua-platform

    cd_payload = {
        "task_type": "kasada_cd",
        "ct": ct,
        "st": st,
        "fc": fc,
        "s": "d49a6b7bf59bb6f5ff2a17caae757f01bc7f5509551e2b34fa641922ca147525"
    }
    cd = run_task(cd_payload) # Get the x-kpsdk-cd

    cookies = {
        'ak_bmsc_fl_com-ssn': ct,
        'ak_bmsc_fl_com': ct,
    }

    headers = {
        'accept': 'application/json',
        'accept-language': 'undefined',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'newrelic': 'eyJ2IjpbMCwxXSwiZCI6eyJ0eSI6IkJyb3dzZXIiLCJhYyI6IjI2ODQxMjUiLCJhcCI6IjY1NTU1OTQxMSIsImlkIjoiMTQwNWRmNzI4OTk2ZDk5ZSIsInRyIjoiZGJhN2U3Y2E1ZmNjODAxOWQ5ODU1OWEyM2YwODA0YzEiLCJ0aSI6MTc3MDI1Njc1OTA3NCwidGsiOiIzNjcxMDc3In19',
        'origin': 'https://www.footlocker.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.footlocker.com/giftcards/checkbalance.html',
        'sec-ch-ua': sec_ch_ua,
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': sec_ch_ua_platform,
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'traceparent': '00-dba7e7ca5fcc8019d98559a23f0804c1-1405df728996d99e-01',
        'tracestate': '3671077@nr=0-1-2684125-655559411-1405df728996d99e----1770256759074',
        'user-agent': user_agent,
        'x-api-lang': 'en-US',
        'x-csrf-token': 'b65741ed-498a-4993-a911-ebce0469bffa',
        'x-fl-request-id': '485cd910-0236-11f1-b540-cf0d6df02ecc',
        'x-kpsdk-cd': cd,
        'x-kpsdk-ct': ct,
        'x-kpsdk-h': h,
        'x-kpsdk-v': v,
    }

    json_data = {
        'number': '6145751246011135',
        'pin': '00692200',
    }
    from curl_cffi import requests as c_requests
    response = c_requests.post(
        'https://www.footlocker.com/zgw/carts/co-cart-aggregation-service/site/fl/giftcard/check-balance',
        cookies=cookies,
        headers=headers,
        json=json_data,
        proxy=PROXY,
        impersonate='chrome136'
    )
    print(response.text)