# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your_token"                                 # Access token (sent as x-api-key)
TIMEOUT  = 60                                           # Timeout (seconds)

PROXY = "http://user:pass@host:port"

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    
    # Task JSON payload
    ct_payload = {
        "task_type": "kasada",
        "proxy": PROXY,
        "target_url": "https://www.godaddy.com/",
        "protected_api_domain": "sso.godaddy.com",
        "kasada_js_domain": "sso.godaddy.com"
    }
    ct_results = run_task(ct_payload)
    print(ct_results)
    fc = ct_results.get('x-kpsdk-fc')
    st = ct_results.get('x-kpsdk-st')
    ct = ct_results.get('x-kpsdk-ct')
    cd_payload = {
        "task_type": "kasada_cd",
        "ct": ct,
        "st": st,
        "fc": fc,
        "site": "godaddy"
    }
    cd = run_task(cd_payload)
    headers = {
        'x-kpsdk-ct': ct_results.get('x-kpsdk-ct'),
        'sec-ch-ua-platform': ct_results.get('sec-ch-ua-platform'),
        'Referer': 'https://sso.godaddy.com/?realm=idp&app=venture-redirector&path=%2F%3Freferrer%3Dsso',
        'x-kpsdk-h': ct_results.get('x-kpsdk-h'),
        'sec-ch-ua': ct_results.get('sec-ch-ua'),
        'sec-ch-ua-mobile': '?0',
        'traceparent': '00-235fd8eda26d85f8bc36efb68721199e-3748bf6c792752e9-01',
        'x-kpsdk-v': ct_results.get('x-kpsdk-v'),
        'x-kpsdk-cd': cd,
        'User-Agent': ct_results.get('user-agent'),
        'accept': 'application/json',
        'content-type': 'application/json',
    }

    json_data = {
        'checkusername': 'a78yuh3@gmail.com',
    }
    from curl_cffi import requests
    response = requests.post('https://sso.godaddy.com/v1/api/idp/user/checkusername', headers=headers, json=json_data, proxy='http://127.0.0.1:8989')
    print(response.text)