# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json
from curl_cffi import requests as c_requests

BASE_URL = "https://riskbypass.com"                     # API base URL
TOKEN    = "Your Token"                                 # Access token (sent as x-api-key)
TIMEOUT  = 60                                           # Timeout (seconds)
PROXY    = "http://username:password@host:port"         # Proxy string

def get_ct():
    # Task JSON payload
    payload = {
        "task_type": "kasada",
        "proxy": PROXY,
        "target_url": "https://kick.com/",
        "protected_api_domain": "kick.com",
        "kasada_js_domain": "kick.com"
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

def get_cd(ct, st, fc, site='twitch'):
    # Task JSON payload
    payload = {
        "task_type": "kasada_cd",
        "ct": ct,
        "st": st,
        "fc": fc,
        "site": site
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    # kasada-cd api is free if you contact us
    kasada_args = get_ct()
    ct = kasada_args['x-kpsdk-ct'] # Get the x-kpsdk-ct
    st = kasada_args['x-kpsdk-st'] # Get the x-kpsdk-st
    v = kasada_args['x-kpsdk-v'] # Get the x-kpsdk-v
    h = kasada_args['x-kpsdk-h'] # Get the x-kpsdk-h
    fc = kasada_args['x-kpsdk-fc'] # Get the x-kpsdk-fc
    cd = get_cd(ct=ct, st=st, fc=fc) # Get the x-kpsdk-cd
    user_agent = kasada_args['user-agent'] # Get the user-agent
    sec_ch_ua = kasada_args['sec-ch-ua'] # Get the sec-ch-ua
    sec_ch_ua_platform = kasada_args['sec-ch-ua-platform'] # Get the sec-ch-ua-platform

    headers = {
        'accept': 'application/json',
        'accept-language': 'en',
        'authorization': 'Bearer eyJpdiI6InRqWDFOQkNOSTE1bGx5RVBoQloyeFE9PSIsInZhbHVlIjoiNGJhVTFHN1VFb2NJK1puMlhTRFBZN3hQYm5BS2dsM0Q3T0YxbWkyeEpZTm1PbysreVFBWDlPSWI4VkRrNDVWbHBBdEtjc3FVb08xd0hIeE0vSXE5Wi9yYWRoSHB4Q1YzcFd0ZGJXZlBuOU1JY0l4WFkwa0tZUkoyQ3Fyak14TEEiLCJtYWMiOiIyM2EwZjRlZGRiNDlkOWJiZjk5YTIyZTFhODZkNGY5MGEzZDVlYTUwYWQ2Y2ZjMDhiOTk3OTc2MTE5MTFkNjUyIiwidGFnIjoiIn0=',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'origin': 'https://kick.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://kick.com/',
        'sec-ch-ua': sec_ch_ua,
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': sec_ch_ua_platform,
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': user_agent,
        'x-kpsdk-cd': cd,
        'x-kpsdk-ct': ct,
        'x-kpsdk-h': h,
        'x-kpsdk-v': v,
        'x-xsrf-token': 'eyJpdiI6InRqWDFOQkNOSTE1bGx5RVBoQloyeFE9PSIsInZhbHVlIjoiNGJhVTFHN1VFb2NJK1puMlhTRFBZN3hQYm5BS2dsM0Q3T0YxbWkyeEpZTm1PbysreVFBWDlPSWI4VkRrNDVWbHBBdEtjc3FVb08xd0hIeE0vSXE5Wi9yYWRoSHB4Q1YzcFd0ZGJXZlBuOU1JY0l4WFkwa0tZUkoyQ3Fyak14TEEiLCJtYWMiOiIyM2EwZjRlZGRiNDlkOWJiZjk5YTIyZTFhODZkNGY5MGEzZDVlYTUwYWQ2Y2ZjMDhiOTk3OTc2MTE5MTFkNjUyIiwidGFnIjoiIn0=',
    }

    json_data = {
        'email': 'a123456789@gmail.com',
        'password': 'znjaAsd..',
        'isMobileRequest': True,
    }

    response = c_requests.post('https://kick.com/mobile/login', headers=headers, json=json_data, proxy=PROXY)
    print(response.text)