# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json
from curl_cffi import requests as c_requests

BASE_URL = "https://riskbypass.com"                     # API base URL
TOKEN    = "Your Token"                                 # Access token (sent as x-api-key)
TIMEOUT  = 60                                           # Timeout (seconds)
PROXY    = "http://username:password@host:port"         # Proxy string

def get_ct():
    # Task JSON payload
    payload = {
        "task_type": "kasada",
        "proxy": PROXY,
        "target_url": "https://accounts.nike.com/lookup?client_id=4fd2d5e7db76e0f85a6bb56721bd51df&redirect_uri=https://www.nike.com/auth/login&response_type=code&scope=openid%20nike.digital%20profile%20email%20phone%20flow%20country&state=8e030e77a47d4c629b7aad51dc087015&ui_locales=en-US&code_challenge=J47KwMAQnYRH4kN8lZAlk-0Vr38k5n0AqQkotv1V1VU&code_challenge_method=S256",
        "protected_api_domain": "accounts.nike.com",
        "kasada_js_domain": "accounts.nike.com"
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

def get_cd(ct, st, fc, site='nike'):
    # Task JSON payload
    payload = {
        "task_type": "kasada_cd",
        "ct": ct,
        "st": st,
        "fc": fc,
        "site": site
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    # kasada-cd api is free if you contact us
    kasada_args = get_ct()
    ct = kasada_args['x-kpsdk-ct'] # Get the x-kpsdk-ct
    st = kasada_args['x-kpsdk-st'] # Get the x-kpsdk-st
    v = kasada_args['x-kpsdk-v'] # Get the x-kpsdk-v
    h = kasada_args['x-kpsdk-h'] # Get the x-kpsdk-h
    fc = kasada_args['x-kpsdk-fc'] # Get the x-kpsdk-fc
    cd = get_cd(ct=ct, st=st, fc=fc) # Get the x-kpsdk-cd
    user_agent = kasada_args['user-agent'] # Get the user-agent
    sec_ch_ua = kasada_args['sec-ch-ua'] # Get the sec-ch-ua
    sec_ch_ua_platform = kasada_args['sec-ch-ua-platform'] # Get the sec-ch-ua-platform

    headers = {
        'accept': '*/*',
        'accept-language': 'en',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'f-sdk-c': 'fb0cc6842889489faff0c86ef63577d7_1764311490141_226_dUAL43-m4_27ck_prFqZWgxJ40=-4387-v2_tt',
        'origin': 'https://accounts.nike.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://accounts.nike.com/lookup?client_id=4fd2d5e7db76e0f85a6bb56721bd51df&redirect_uri=https://www.nike.com/auth/login&response_type=code&scope=openid%20nike.digital%20profile%20email%20phone%20flow%20country&state=8e030e77a47d4c629b7aad51dc087015&ui_locales=en-US&code_challenge=J47KwMAQnYRH4kN8lZAlk-0Vr38k5n0AqQkotv1V1VU&code_challenge_method=S256',
        'sec-ch-ua': sec_ch_ua,
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': sec_ch_ua_platform,
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'same-origin',
        'sec-fetch-site': 'same-origin',
        'user-agent': user_agent,
        'x-kpsdk-cd': cd,
        'x-kpsdk-ct': ct,
        'x-kpsdk-h': h,
        'x-kpsdk-v': v,
        'x-nike-ux-id': 'com.nike.unite',
    }

    json_data = {
        'credential': 'a123456789@gmail.com',
        'client_id': '4fd2d5e7db76e0f85a6bb56721bd51df',
    }

    response = c_requests.post('https://accounts.nike.com/credential_lookup/v1', headers=headers, json=json_data, proxy=PROXY)
    print(response.text)