# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = "http://username:password@host:port"

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    ct_payload = {
        "task_type": "kasada",
        "proxy": PROXY,
        "target_url": "https://www.sephora.com/beauty/giftcards",
        "protected_api_domain": "www.sephora.com",
        "kasada_js_domain": "www.sephora.com"
    }
    ct_result = run_task(ct_payload)
    if not ct_result:
        raise Exception("Failed to get ct_result")

    ct = ct_result['x-kpsdk-ct'] # Get the x-kpsdk-ct
    st = ct_result['x-kpsdk-st'] # Get the x-kpsdk-st
    v = ct_result['x-kpsdk-v'] # Get the x-kpsdk-v
    h = ct_result['x-kpsdk-h'] # Get the x-kpsdk-h
    fc = ct_result['x-kpsdk-fc'] # Get the x-kpsdk-fc
    user_agent = ct_result['user-agent'] # Get the user-agent
    sec_ch_ua = ct_result['sec-ch-ua'] # Get the sec-ch-ua
    sec_ch_ua_platform = ct_result['sec-ch-ua-platform'] # Get the sec-ch-ua-platform

    cd_payload = {
        "task_type": "kasada_cd",
        "ct": ct,
        "st": st,
        "fc": fc,
        "s": "35ed43ab433ffeac189a29ed5fcf9417b3c408f22a3225a0ff76e0b5347e2e8a" 
    }
    cd = run_task(cd_payload) # Get the x-kpsdk-cd

    cookies = {
        'akamweb': 'C',
        'device_type': 'desktop',
        'site_locale': 'us',
        'site_language': 'en',
        'rcps_cc': 'true',
        'rcps_po': 'true',
        'rcps_ss': 'true',
        'current_country': 'HK',
        'rcps_product': 'true',
        'rcps_profile_account_group': 'true',
        'rcps_profile_bi_group': 'true',
        'rcps_profile_info_group': 'true',
        'rcps_profile_shipping_group': 'true',
        'rcps_sls': 'true',
        'rcps_profile_userprofile_group': 'false',
        'rcps_ccap': 'true',
        'rcps_cctk': 'false',
        'rcps_ccappl': 'false',
        'rcps_beauty_chat': 'true',
        'rcps_full_profile_group': 'true',
        'rcps_basket': 'true',
        'adbanners': 'on',
        'AKA_A2': 'A',
        'bm_ss': 'ab8e18ef4e',
        'bm_so': 'E65BAD0E9C71808B9E2811BAEB7EA3DA32E72211DB824E9AA5A32183F46A936A~YAAQqrkhFzEzaNqbAQAA3co7DgaiOq6dEwOft2Tmz/GFkMmU9aXGCUjHDeqqwDWwqhvcu/BAV062yLXAQuYwPw8bUw/sev+WRElFYDBTCjaRkyY246g7iEll8CyRRKHVQkyJdqzR3OlZLADBuw9J10xeDpSswjx59B7gaD137k6DXjHelZWb9f+IjfmF6AhuuskFqUXKDSHc5B5OxsBloJUSB9Va5tiAGtKizw2vvd9fqGdFvfmD6EG0nceeTCLsIOuffuxOaXhRvcnhG3cYnCCogGF54KEKmz66vSRdI9e+sOKBB7zCpGmplR2Qv7RGLwC+lsTzA7cirtnmUKiQ3V0mrKp7eGsZosRYn/8gslx+znLMu5p25MuujDz67K2lFUfaVUfLP4+kmWBYRJnisFdqFcjgZyrnznPzTk6bS3k4WKZTPwTEr0JSt9WBreW6BUG+caKTLz3kgAPj2HdhhQ==',
        'bm_sz': '053EBB0F6D7C04236E496FE00639D647~YAAQqrkhF+rAaNqbAQAAgYhBDh5wGuCy9EDuLmTQn6BvPAqdTjrbW9NTiNaQO8VYZp1w3XKM1chENEao5UWZSTxkFEoEs4vBSDD8DyOpsda2+cfDgWaDsPzL03mK0cT68Mm4MC265aieavbNh17o05kraGkoM0bTO3VFbl2/ZswDxsuBt9UZZoqHRvzs4xM6lmvClS0QuJhwo0ijvpxzn2njwvYcjREKW86m3cOh0c8/Q0W3qbQO71RoQMFGHd7O9aMHVQcDurltABe3GY40s4D3z8V72Wi0YumXRRkuA48RF9mPXKkaYvTh9/RGo8HR7vU8Dl7wD4LwRI660yarkRo2tmb+1+M7SJzFSMUafpTODNlCi9z67bKCym24EXMJktGnuwlv8OO0rgh3RpYbSHLifxCHCGuM20Tv2VMVag==~3162422~3556914',
        'PIM-SESSION-ID': 'EukvsEOI7wiN1SHk',
        'at_check': 'true',
        'ConstructorioID_client_id': '33027b53-ab0b-417c-bbfd-e02d4aa7ba8c',
        'bm_lso': 'E65BAD0E9C71808B9E2811BAEB7EA3DA32E72211DB824E9AA5A32183F46A936A~YAAQqrkhFzEzaNqbAQAA3co7DgaiOq6dEwOft2Tmz/GFkMmU9aXGCUjHDeqqwDWwqhvcu/BAV062yLXAQuYwPw8bUw/sev+WRElFYDBTCjaRkyY246g7iEll8CyRRKHVQkyJdqzR3OlZLADBuw9J10xeDpSswjx59B7gaD137k6DXjHelZWb9f+IjfmF6AhuuskFqUXKDSHc5B5OxsBloJUSB9Va5tiAGtKizw2vvd9fqGdFvfmD6EG0nceeTCLsIOuffuxOaXhRvcnhG3cYnCCogGF54KEKmz66vSRdI9e+sOKBB7zCpGmplR2Qv7RGLwC+lsTzA7cirtnmUKiQ3V0mrKp7eGsZosRYn/8gslx+znLMu5p25MuujDz67K2lFUfaVUfLP4+kmWBYRJnisFdqFcjgZyrnznPzTk6bS3k4WKZTPwTEr0JSt9WBreW6BUG+caKTLz3kgAPj2HdhhQ==~1769765326428',
        'SephSession': '1c747e03-7c23-4e64-a56d-274e026f0124',
        'akavpau_akaau': '1769765927~id=e1ce1b6de68e7d7a6c46c7204602f2e0',
        'AMCVS_F6281253512D2BB50A490D45%40AdobeOrg': '1',
        'preferredStore': 'undefined',
        'trackIntlPopup': 'true',
        'rxVisitor': '1769765327077833OIPIOFE70M1701O3ESEP6DC3AKN19',
        'dtSa': '-',
        's_ecid': 'MCMID%7C12778030497868359431790311679024760154',
        'AMCV_F6281253512D2BB50A490D45%40AdobeOrg': '1585540135%7CMCIDTS%7C20484%7CMCMID%7C12778030497868359431790311679024760154%7CMCAAMLH-1770370126%7C3%7CMCAAMB-1770370126%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1769772528s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C4.4.0',
        'RT': '"z=1&dm=www.sephora.com&si=65d133b8-f634-43b8-b4a3-3ad05f5ffa6c&ss=ml0okw40&sl=1&tt=3l0&bcn=%2F%2F173bf10b.akstat.io%2F&ld=3l3"',
        'ak_bmsc-kp-ssn': ct,
        'ak_bmsc-kp': ct,
        's_visit': '1',
        'mp_sephora_mixpanel': '%7B%22distinct_id%22%3A%20%2219c0e3bdc07176f-0162c207fe6eab-26061d51-144000-19c0e3bdc081fe0%22%2C%22bc_persist_updated%22%3A%201769765329975%2C%22hasLovesList%22%3A%20false%7D',
        'kampyle_userid': '62ff-a350-429a-5756-806a-0e9a-4514-877d',
        'bc_invalidateUrlCache_targeting': '1769765330099',
        'kampyleUserSession': '1769765330186',
        'kampyleUserSessionsCount': '1',
        'kampyleUserPercentile': '42.39967502909151',
        'kampyleSessionPageCounter': '1',
        'ADID': 'a2ce37f70fa2230d0f642d2c8d038d9c214d2ed6969e791dbffca4969f4901d0',
        '_tt_enable_cookie': '1',
        '_ttp': '01KG73QQAMDEAE3AYF782441FF_.tt.1',
        'mboxEdgeCluster': '35',
        'mbox': 'session#6f4fd90e4eb941f1a66b0305e4ba562a#1769767191|PC#6f4fd90e4eb941f1a66b0305e4ba562a.35_0#1833010131',
        'ngp_userreg': 'true',
        'bluecoreNV': 'true',
        'rcps_frictionless_checkout': 'true',
        '_rdt_uuid': '1769765330601.9366ba7f-db91-4655-af59-65a88f89d858',
        '_sp_ses.236b': '*',
        '_sp_id.236b': 'e8e72f49-a99b-4765-84b2-6f85aeec2f76.1769765331.1.1769765331.1769765331.281e3d1a-a714-4911-93e0-fbeee8a86467',
        'ATG_ORDER_CONTENT': '',
        'CNC_ORDER_CONTENT': '',
        'bm_s': 'YAAQqrkhF7E1aNqbAQAAs+A7DgSTfVL5Uvp6AFlJYZhPHI56La+H+MznnurUbzjz3WIiEDtrwkJAEBoolnE1CVMyGPMId8sqV6A/jyaxjFHT1uuehwb/VA7sh0/90qgH9PMwYbFBNLsPo1oyl2rPGSuQBjqou69olf7AKgHuKsXGXNhEdD2nwVuzQsqOYqlho6EA66MPd0SmJ4+E125daR1FDYoZZYiXynhQE3+QOiodOBf5/CQcWmg5W/IhWM/BauBoAt0BnAAa8zsdHVh8QLaOCizURJmsXKNCEQ5deL7YweaOZdXlQeIr0s3RGIvwvtq0O6vWgvWkW3vbPLtuZotSWxegFL5AFLT5MdE0KmEO4IaL0y6RJj7MNGAZBI3DZhEgLnFjVLFs4QFezLRMjKSb/gorIRkjr6ZIkVHvlZnjo/Nul0TDtCni1BzMYhkh7uksQJM28iNQPOHE1bMTK4wrDDGGk9vckkZd2DQUoGUO+20dB4CSiIxoohRDvM9vCaevzqjo91LXj9VYecFnJkQj6vpoX9r3x0CIoX3hidE2hG5LBdQWgUsS+KN7gP+6xQjHrua64o44VhUUzHr0',
        '_gcl_au': '1.1.2017101209.1769765331',
        '_gid': 'GA1.2.1096083313.1769765331',
        '_cs_mk': '0.26528788692813476_1769765331348',
        's_cc': 'true',
        '_scid': '1YHxqpxp4uvDyp4vlmuBKbyWvS6n0hfE',
        '_scid_r': '1YHxqpxp4uvDyp4vlmuBKbyWvS6n0hfE',
        'dtCookie': 'v_4_srv_6_sn_9OQR7PS8NE0HAO4MH6CPFQ8UNVJJJB0V_app-3A010ad61344e68aed_1_ol_0_perc_100000_mul_1',
        '_sp_ses.932a': '*',
        '_sp_id.932a': 'b9e9e00b-4b02-40f9-977f-932fbb0aa6fb.1769765332.1.1769765332.1769765332.57098616-2950-4315-bfd1-8d091e626efb',
        '_ScCbts': '%5B%5D',
        '_uetsid': '16fab9e0fdbe11f0a2493570354d31fd|13z2aho|2|g35|0|2221',
        'sti': '41422792-d7a3-43e2-a362-a2bab3d9c49b',
        'ssi': '41422792-d7a3-43e2-a362-a2bab3d9c49b.1769765332268',
        '_uetvid': '16faca60fdbe11f0b2288968f9d18bda|la3isx|1769765332512|1|1|bat.bing.com/p/insights/c/n',
        '_sctr': '1%7C1769702400000',
        'ab.storage.sessionId.476615b3-3386-4e1c-a9fd-7e174eb9b8de': '%7B%22g%22%3A%22fccf16a6-9d3e-9c20-5623-de75d37c7c33%22%2C%22e%22%3A1769767136112%2C%22c%22%3A1769765336112%2C%22l%22%3A1769765336112%7D',
        'ab.storage.deviceId.476615b3-3386-4e1c-a9fd-7e174eb9b8de': '%7B%22g%22%3A%22fee4362e-1cd4-3596-ebf3-735cedb38533%22%2C%22c%22%3A1769765336114%2C%22l%22%3A1769765336114%7D',
        '_fbp': 'fb.1.1769765336172.53583685769363223',
        '_ga': 'GA1.1.2025151228.1769765331',
        '_pin_unauth': 'dWlkPU1ESXpNemN6TkdNdFlqSXdaaTAwTXpZekxUaGtZekV0WVRKak1qTTBaVGswTm1GbQ',
        'forterToken': 'd8e977a3b1b44b4fb976b996f3a7f411_1769765334370__UDF43-m4_23ck_',
        '_ga_HX1JZMWBCJ': 'GS2.1.s1769765336$o1$g1$t1769765348$j48$l0$h628972699',
        's_ips': '2130',
        's_ppv': 'contentstore%253Abuying%2520guides%253Ashopping%2520made%2520easy-gift%2520cards%253A*%2C46%2C46%2C46%2C2130%2C6%2C2',
        '_abck': 'BE9A3743CA1B54EAA60B375296F78A57~-1~YAAQUr0oF49u/OqbAQAAMvpQDg/hV6YlEQpDX50yQxaVuwGAOgC0FQhWH9znFF1+ecgrKMXar7u0h2b8b/ROPgzguLbJktLLulphfT7n8kDr1n5nfPgwqIpHVSj6Y6bvRtv5YDjTeglWrzHqPCunTZtdKriK2lciptCZIYtBa6ceUBrC+c0QLgI2f/S9Kv8r083xhw4fqxr1SFYRP0wJu90hmWbPxRCqj6yg80SNm4bF1mPODRRb3LzjaIBvlCXyK4/S/Qmj+6+ga6eqH9GYY4SByfU5J9co9JLApZ4MMznUMXjg3fjE5ily84LZ2YtLTPF27ZLQxxYVTEeMj1RVUu7Kce6vb/3yZ6jjxH56PLAgymNShcRrUIaaR+wwM5tUSW66AacsPG+dBLwa2gnvS1u2aPzJuze8s2URsNnyAqkwBrSPouU9XgRUvWUevitj9gf7OpBdkyitZxI44i2ti1vME7p8SzzYJ479Pt+vZRvf8JFiF7wuVi1UttSYF3GZv7LXU+QMQOBhM8qxtApAd35hlWvPR9vtPWCWBNf0M3tefjqhlyTfVuO4GgyHsX7f6X0xPorho879u4ygB7ODiu3s24tQbkAcBkuIoAnPcu1cZTY1WABVqTyzcLJc/NpYwo6rn7x13uClh6v+W/0NzuSWl+MaGlX5+urUYukTyGoqzkyPX4fbsA8wJ8Qq0id9T3SH0asy19ht6QBi5qTNs9HXO3fBxyxALXpcJnJz1kkE5avAuYFE+R8djdhlxui860nb2VHYD0TNbMWkDV8vou+pIR4TQwj6/QMW35KADpUZl4d6CkmSYSOmaNZa14JSqWRVDPGw8o4aetN2FdnAfIlSHnMORtlfejD0Wcx5EYA8tUdQbV2ApxvzJdV89GvL7kCgIHzWrCrYiiPlMvo7DaVQLuBLR1S31joR8ijj1qMGZ+1hitnQEHHOGck/S2yWqd4rvwn3P2YLbzHzfuQggtFT4lJ59SKwO9N0AviNJgHbfFz42Hsllt+H8A==~-1~-1~1769768926~AAQAAAAF%2f%2f%2f%2f%2fyGCMHhnV9mQ8tNH+G5RsN0mXfIG0qjDVkxoSrIi08VoSz17u++HCyESbQsI+i3fXlF7LEQMYS51gHlyEjhbGmIlA+YOn1nnkEq9pZ+0BlNLeDwtYcn33z%2foh6GD4i30Gt4fDi0%3d~1769766773',
        'ttcsid': '1769765333952::3Ez6z1OfAZ6l5Hvzwqbn.1.1769765377435.0',
        'ttcsid_C4E2IGE9UAPKMTRVH0H0': '1769765333953::1y9k7uZ6gYAu8aOrJOfT.1.1769765377436.1',
        's_sq': 'sephoracom%3D%2526c.%2526a.%2526activitymap.%2526page%253Dcontentstore%25253Abuying%252520guides%25253Ashopping%252520made%252520easy-gift%252520cards%25253A%25252A%2526link%253DCheck%252520Balance%2526region%253DBODY%2526pageIDType%253D1%2526.activitymap%2526.a%2526.c%2526pid%253Dcontentstore%25253Abuying%252520guides%25253Ashopping%252520made%252520easy-gift%252520cards%25253A%25252A%2526pidt%253D1%2526oid%253DCheck%252520Balance%2526oidt%253D3%2526ot%253DSUBMIT',
        's_tp': '4654',
        'rxvt': '1769767177613|1769765327078',
        'dtPC': '6$365327075_566h45vCEARCHAKRDIKDAIAGQMCMEKTEUEGMKMN-0e0',
    }

    headers = {
        'accept': '*/*',
        'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
        'cache-control': 'no-cache',
        'content-type': 'text/plain;charset=UTF-8',
        'origin': 'https://www.sephora.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.sephora.com/beauty/giftcards',
        'sec-ch-ua': '"Not(A:Brand";v="8", "Chromium";v="144", "Google Chrome";v="144"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'seph-access-token': 'eyJhbGciOiJSUzI1NiJ9.eyJBdXRoRGF0YSI6eyJkZXZpY2VJZCI6ImEyY2UzN2Y3MGZhMjIzMGQwZjY0MmQyYzhkMDM4ZDljMjE0ZDJlZDY5NjllNzkxZGJmZmNhNDk2OWY0OTAxZDAiLCJ1dWlkIjoiNDllYWVkMWItMDlkZS00MTA2LThmZjAtNGE1MDU2OTBlYjRkIiwicHJvZmlsZVNlY3VyaXR5U3RhdHVzIjowLCJyb2xlIjoiY2xpZW50In0sImlzcyI6IkF1dGhTZXJ2aWNlIiwiZXhwIjoxNzY5NzY4OTMwLCJpYXQiOjE3Njk3NjUzMzB9.C5ajXo_L9Lkte0ackrRwGlZpY_7DSde1NAn1W4eVKtqXWgKXyjv6LFOxAjDzB8XdqnXgkWQcmG51ED8EqvDHQstIDmL-gE-qVfJjCeIe5rC6j0W6FNx9ujee0La8TITCGWIBEW6lKVQThcdsoiYXAlCnnrpWi6UVuJOhRW3PldoDKwyhkJj7UI1r0VG6e2Xvn9Njn5OFLJ4OEWuhuVUzlUnhyINxmGI8V_QMrP_9Pna0BDk7WS0CgetC6enGwaFm5GMurghYppkKdlD7xEcZkLdhdkljG3YS74aX9hzAqynVVA4EpKZpBozKmVgruaExyYHAVvcHz7cdottYGXyItaRry3k03HDk8I4KHRBpddKA9_x8wKthSRtoTs6w4SKC3BqU9iBYhsDYPYH8oj03FK173siqVWgfBhwtcpIA7RjTfyAhb2etuihqFVWDLEFhpr4sBeS0S3EyZrkof9qp6RdxDDyD59kFdzKQjpPHlA6JPVYUFlzRGupmAzGZkZR3eSzNCC_q_-Uw4lhXG1ccuBqdOgtJrA47CdaYNS7bFYlrYZ-iXn-i83dB7oR0A4_Q0SSdyewoO8ZUKm_iV1JooZ3-41r-zT3wcjWuzMoH_KC_DgFDjMfo26xtPtQQ3GY-MHyWwIoR4TiVC-O5xTdmcOeb4gS_lSyedm3IDeX-wQA',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36',
        'x-api-key': 'nQc7BFt78yJBvfYDKtle9APd5RrX984i',
        'x-dtpc': '6$365327075_566h45vCEARCHAKRDIKDAIAGQMCMEKTEUEGMKMN-0e0',
        'x-kpsdk-cd': cd,
        'x-kpsdk-ct': ct,
        'x-kpsdk-h': h,
        'x-kpsdk-v': v,
    }

    data = '{"gcNumber":"2767433212321123","gcPin":"12342345","captchaToken":"0cAFcWeA4vB5CXFGa1hTT78cGfAu0s5Cz7EOT-uW73R60rwc3FnBo__mM1DsdOtEs4OHNFBLg-iDJLGY0ogbTlRs7o-3E53CmVOXRjun5K6hhxkgFR2vHB33uZo9Y7A6MPENZ-X29QsA1XUKKKO3tzCATUZiMZiplwP6rez_vc3XEjDfWfX5eStDlDOpoA8qEQk6DJgdBjtQA_Nl55gXPgvZdixUY50PX3XIGeTDeeKy43iG1gstTkNkdm1vcl0QnqODjJr9tKZdVd3SLujDJQSzpADhC1m0zv-Gsk3mg7rr88mPai69iUA137QVPUq5lpR-Ko-KKxc1rKwHY8LbRT1qqLp2aqIt4v1qkZiLoRBPfM7B-hV9YeXa7KTaxcYyHUPh2Xx4C06p27NuAvItPjjdufycxFEW6_z_nWvytfLZq_1NK6mhdwCIugAupdW-ZnzwrWRigzmXtePprXDmmyDr5VsRY2Y8jY-ikAvPNSOpcmpcROBDLcoHudJycpQRx24lOF5kkhuH2jhYaiJn99UniK6eP97aw5WtZtZ291i6De3U8erMwftStIxNQ8Hn70PagYpTZLcfvlrIIXXKd6HGr0HPbeqcgPnUl5qrYAvxeeNJCNoVNpgBu9OqozoYhBar8nnbJ8Hx2l6Aht4Ju8BO9slH5VGJRchRa-xWtcUcNpGak4ouXUgy95_4tzrqpN0csIP7XtSUesjfDQ1VdLR5TEwXKn42Jt6GdU3WtLtZkzZgbYspLln7u87f1mxfWy0MjDiFmaxmOoUNnaMmnR8u3CnEGpHA6lXs4NzmPvLNzrlP8NCtOR9yHfl_ozrVmrmIYVIwTKXaV6VJPPx3eGddRHXH5n2uPKUoRpeCmHP_DXQx2Jj4RxZ3N8f7aZMHG_6kY1TBgrGrZbFzlsrwK8MPOyUBAJCX18s543Y8IVQMqsQ_LBOMh7bBNMzxUEee7xbTCgQ1UqV4RmhX0-T2LkX6vSaPSux3uEHC19vA0RcLIdGOMreSr-5duj5crStv_5ltyTqqlRfol21Q2Hu7vqZ-1yqXk7kT9wcHa_S6hgLgpn7Q2MgR3VH_8"}'
    from primp import Client
    client = Client(impersonate='chrome_133', proxy=PROXY)
    response = client.post('https://www.sephora.com/api/giftcard/balance', cookies=cookies, headers=headers, content=data.encode())
    print(response.status_code)
    print(response.text)