# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json
from curl_cffi import requests as c_requests

BASE_URL = "https://riskbypass.com"                     # API base URL
TOKEN    = "Your Token"                                 # Access token (sent as x-api-key)
TIMEOUT  = 60                                           # Timeout (seconds)
PROXY    = "http://username:password@host:port"         # Proxy string

def get_ct():
    # Task JSON payload
    payload = {
        "task_type": "kasada",
        "proxy": PROXY,
        "target_url": "https://www.twitch.tv/",
        "protected_api_domain": "gql.twitch.tv",
        "kasada_js_domain": "k.twitchcdn.net"
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

def get_cd(ct, st, fc, site='twitch'):
    # Task JSON payload
    payload = {
        "task_type": "kasada_cd",
        "ct": ct,
        "st": st,
        "fc": fc,
        "site": site
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    kasada_args = get_ct()
    ct = kasada_args['x-kpsdk-ct'] # Get the x-kpsdk-ct
    # ct = '0OzDMhCPBpv5mEErRFlTMpOHqoUGCo1WQuiF5zkTTUT4ZDTqxymsy40zuerwP6AKLRmorG33UeZBf1AfNFQYDDNMqEDWKgfw3p4fZaOqCumMGYcppVWbHQoHoZJSqhSwzbAMKU6diB3dr96j7hTkoW3iuN7syVF49OMD2wqW0e8ipTQ6'
    st = kasada_args['x-kpsdk-st'] # Get the x-kpsdk-st
    v = kasada_args['x-kpsdk-v'] # Get the x-kpsdk-v
    h = kasada_args['x-kpsdk-h'] # Get the x-kpsdk-h
    fc = kasada_args['x-kpsdk-fc'] # Get the x-kpsdk-fc
    cd = get_cd(ct=ct, st=st, fc=fc) # Get the x-kpsdk-cd
    user_agent = kasada_args['user-agent'] # Get the user-agent
    sec_ch_ua = kasada_args['sec-ch-ua'] # Get the sec-ch-ua
    sec_ch_ua_platform = kasada_args['sec-ch-ua-platform'] # Get the sec-ch-ua-platform

    headers = {
        'accept': '*/*',
        'accept-language': 'en',
        'cache-control': 'no-cache',
        'client-id': 'kimne78kx3ncx6brgo4mv6wki5h1ko',
        'client-request-id': 'OLLeT9axGzXDvwN3T4dp9XKHJ3wiI31a',
        'client-session-id': 'a099553b2749aca0',
        'client-version': '87438f7e-baa7-44a5-ad55-787e0a959b1d',
        # 'content-length': '0',
        'origin': 'https://www.twitch.tv',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.twitch.tv/',
        'sec-ch-ua': sec_ch_ua,
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': sec_ch_ua_platform,
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': user_agent,
        'x-device-id': 'nUBB0WF39t2ZChA888eq66vxi01Wx3NM',
        'x-kpsdk-cd': cd,
        'x-kpsdk-ct': ct,
        'x-kpsdk-h': h,
        'x-kpsdk-v': v,
    }

    response = c_requests.post('https://gql.twitch.tv/integrity', headers=headers, proxy=PROXY)
    print(response.text)