# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, random

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = f'http://username:password@ip:port'  # Must use HK proxy


def run_task(payload):
    
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    # Task JSON payload
    payload = {
        "task_type": "hcaptcha",
        "proxy": PROXY,
        "target_url": "https://accounts.britishairways.com/",
        "site_key": "4d2f4c72-52aa-49f1-8838-fd0f962d0c10"
    }
    result = run_task(payload)

    cookies = {
        'uuid': '08c37a2e-fe44-478d-ad44-b4bd6765e5ab',
        'session_id': 'bdc28083-c975-413d-85f8-f3a8ab02eaaf%3A1769259359437',
        'ens_adobewebsdk': '802780e8-d87d-40a7-820b-bfc469889ac6%3A1769259359436',
        '_fbp': 'fb.1.1769259360739.869019976624296170',
        '_gcl_au': '1.1.1002850520.1769259361',
        '_tt_enable_cookie': '1',
        '_ttp': '01KFR16RKBKYRBQYJDHQPZ941G_.tt.1',
        'QuantumMetricUserID': '3743af9260a627884cdd4630f074fa42',
        'did': 's%3Av0%3A979ef77c-7ed7-4954-be11-14bece278dd1.kwVqYQ%2BPD1i%2FDLW7xCcDGiDgTpcMArqAsH%2BvIIEtRrQ',
        'did_compat': 's%3Av0%3A979ef77c-7ed7-4954-be11-14bece278dd1.kwVqYQ%2BPD1i%2FDLW7xCcDGiDgTpcMArqAsH%2BvIIEtRrQ',
        'AKA_A2': 'A',
        'bm_ss': 'ab8e18ef4e',
        'bm_mi': '73F95EDBEE15662127BDB9F6CE31A06A~YAAQldcLF3W9jeybAQAAUe4v+B7vINRZhJEGQKKSeSilAxAN6JZ1XnSoIySoledT/q4Wq3TRdPsKfvF2D/G7Cibpy16elH8Et9ucONY3jgnJHJxKSjtLqUcOKIIllPOWSvcnr1TI11346aOxp25YfaAmi7vOmT7FkHIydKVV8ymBP53SBmAAtF3UZM1heCbi1cGMYC4nX7rBA/8PG6GiGlpXZOo5k4Y9WtnPg0qLBBVt7eI4U+ssg/jZ8IGlxRWDsFSEtndlbZpG4/54MgV68ow8r/yO6ZVxauv+5HzhZEiRaTIztYRwMHfK/QzH8gB7+gKn1ymM0Gwqvbbfc3QfI2MjCckAt+7QtrVygZ5i~1',
        'bm_so': '5839CF81F22CC851AAF7C1420F06998274AB8557F69B4697D69E82E873554BD3~YAAQldcLF3e9jeybAQAAUe4v+AY4Y2t3EH4qW7J2KukupGIvy1oIErVkIKX7iDBKFebkEUn64uerbUY6+mLTlqgVJfy9BlrOFXEukoUzaaxBRg+5ALHeOp6pvx7JP4oDK3sM8CTquVkGSU3VB0/Za+sfKvGsYdwGLqDOXjgES3WmVmDKmjuzr7tn0x00ryFY3bRZAV67ba+UdEYEe6ydkwBtrNjoFQZzf/5sWL6hIpW9ErjTXmtODQ7FBf5tBrPr3fO/wTQqwdCyXLCYeKMJfvj7iCU9FHs6zyEgL9vS82YKk13wVl9BCR6tCOLrDWuKC7ajrXmDyHdwZU3UbpyGFvX+XdZ4JZgy5NQyYNnuk6rgvJfcxzFOKf3O6OhaDRfVUQ41DQqb/7E5IbQREqFImkJHhK/1+d/R+fD/6tvMlMvZoKadwHM+M07wCN105sFOviYp9eSxVKLItIE3z/o3WGPd59T0Vg==',
        'AMCV_718D3E2F59A96D3B0A495C46%40AdobeOrg': '359503849%7CMCIDTS%7C20480%7CMCMID%7C68074045910881144575677922880180352900%7CMCAID%7CNONE%7CvVersion%7C5.0.1',
        'ak_bmsc': '30A2721B66CF91739492B98490ABE75B~000000000000000000000000000000~YAAQldcLFyq+jeybAQAABfYv+B6B+PO5jOdBIKdsWPjEYd8EBopDlVUIhPEMndiDAt34ZG/N137K+CQZwhqdNZPeT/veecNF1+uMDC7PJI1UEkMCh821w9ImGoGtg8+Rt5XUaOr20OymYFavvQujDvM4RNGkrYHe76ORC8x957seHJEo2ASItMTJT6sFVy7mdvaH9lqo7XpKKIUpy/+5PwVpJzeEeM6W1zVYbjkoSBhXIFTJVCflO7UmN9BWwETzS71HqpCSTk6Eklf2tSfzSNF3NeNAe/SoYhRvO0hAz7LPO/7Ildn2R2/aHQyqERpH/Dth+w9GPuBBAOm0R9Dy7MNwXByy9CePbTt1tpHTJgt07zR0kDja2alhJ4M6sje+Vd18aoi5/TTkveXGbe2bddOdvNqTQ4S/EtRVX00c19v4DLAAb7C3twaJ21ETdimWTeRtuxu350dxtyX9dtAjZEhJgiZRQnbbjVrXImbsT/IgvOu7bubSxL0jImeFnd8c/9TR5eLWtawhCwQqP25PJg==',
        'ttcsid': '1769395452346::pvwyOEDYQEazadxCLuBM.2.1769395452945.0',
        'ttcsid_CJ1QFRRC77U75407KT20': '1769395452345::44FJ87Oheu27cwVL2FRk.2.1769395452946.0',
        'QuantumMetricSessionID': '32ad59db0c47e0612c808fca25dafdfd',
        'kndctr_718D3E2F59A96D3B0A495C46_AdobeOrg_cluster': 'ind1',
        'kndctr_718D3E2F59A96D3B0A495C46_AdobeOrg_identity': 'CiY2ODA3NDA0NTkxMDg4MTE0NDU3NTY3NzkyMjg4MDE4MDM1MjkwMFIRCJbdzYC_MxgBKgRJUkwxMAPwAdeMwMG_Mw==',
        'bm_sz': 'A395908E4DC1745BE62E6EF10F9D5408~YAAQldcLF4+/jeybAQAASAkw+B4WwrciABrazkDY7ulxPYyTAbdr2nBfvw7EdAO3Uio7iHdV19wToC2XWF8umHddlJiCmUR3bO9OHTs8cD7DnyCmnc5vG5e0YsY3o2zUWe7sPUaAj5FofKGsdrPXwB+FeFRXhjIrP0tGJmbkhi1FkWG8TKuBOHTe6lCxQB12EzQEcnakOedl9Apg7oOc8CjB8MFNOH3BscqCOmYxdchYpJxd/p/gnv0foejH1zWRkPn4PnVFMiSmITq0BbGZjJya56ZER3P123mHLXB+QmxznuZjmXRK1M9PouP6be/XFv1AQ3Dld2YlhUmn9b/QayVit+KEXET5ScUanRKZaOK44HstvkmHzQrjWKS609KiO9VAVnRspuu5b033/Yms5gnGMy4q0rAlfMFvdGiPq92xwcvyQ7Db9ZqNAvr3tfNa3aOJQPo=~3360048~3617603',
        'bm_sv': '1301C6B04C085E3C4CF4A0EC392B9F2F~YAAQldcLFy7AjeybAQAACBEw+B46RMHI2tvJ1ZN8Iqm1FkUgTQ5ra8TjqS34cQSHIxESnfjhXBxCkmPvIP+E0cmceID5Wf/37qZNCU+3tmkHMTSWUlDJXAdAFkLo1f6gc9UgAeQiIeuhZZ1Ng1byc99sTu489wnNTWtcH3rLd1oKSNOBa/ex5AQW/wVkcfTvE1SfljelCJw0Cnfz7Zs7wz13rjz8eCuRNYs42KvTcEIsUnt9ONmH/IVV9FDCICJEhDhmFcWXQ/I=~1',
        's_gpv': 'Account%2FLOGINREGISTER',
        '_abck': '264E9799D0EB58D1803A396002CEA7FC~0~YAAQldcLF4LAjeybAQAAQRcw+A942d6o4EhMlN/p/qSpRfpDejeTU4bl/sxP/CkwYzl0XvClebDD20BmhFC0iTdo5VrhVfZWNqpGSIPcotRr+nHEwcTRgrKWNSySHjX0YaQci4medirSoOAaj436Mlu5wzWNXSr2V9iuQnRO4iwGa2Vyxcsjz+KW4R7Kkr4JYD1y4Ha9CkT9HmYpOwqOvSB0HMg/95D6nLpPuMwo+Bf8bLKD24qqC4bVmMoDcroUi2lvYtrELUuBQwWTHJK/kQSZVEdok5qHL51r94MQDao+Z9Jb1CRTjWmdBmgDXN5lrUWhVHdT0WvCBpVJ6qTRxho9MEiaN67sIvednG9RIAeZYNXTg35TYcks3hVLGRFWsPBXS3THNQi1U5+vyAMRBm5bm+Na5euA6Cr0wTY7T03kAvUEsn3dKhbtEBJXu3lZh9oYrz4P4KcjXeo/6uzcKz5UYLvlNy6usISkeltR8fv+tv2od8+Q4NnUhXc4fJ/6naG3Qzs/hnr8yZ/0rjm+Z/w6zY58orx+7wtkiLqn81g1ybGBXARZygNj24lBUh18WUINgIHlcBrUybFGPsToJT8cAli6kh61SzhmjkXf/pcV6mRCqd3c8iIxWVXFk+FWcBlbAIRNjy29G5A+sGGY9CtIRFVLHBm+NkFyjx8ilYaqKVakRvlRFLG9jjNcv7aDokMpIio3kFLEdGh+7YqQj4ikrraHKmZZgEhOvfkAKHFu6Qw0JBo9lMCQNB14NojIJEsKY/CieiP5MTIxr/6pNHWevLDo5gLabxPUrazRozbYMfYDUGexl+7kTNiZn6Up8s/82zuSUSSLPPakLhUuzwwtFftyay8/LpURB/KCEOqI3EZRQkdZ89uSC2DN0IAuocrAJ3qYjp60HA2QG6jaIgb/KqV0SoBlHKTkksQybjGFXg==~-1~-1~1769399050~AAQAAAAF%2f%2f%2f%2f%2fypKf3daX+sUsKBLyjx4jRerwFepGInyZAd8zYmdMJRyleyxS1kYHt6cG58Fsr0msTjfmVtNq+Wesr2BFMKCNCgIPg24FLnOzQcs~-1',
        'bm_s': 'YAAQldcLF6jAjeybAQAANhow+AT2MtIS+akzUTcX2JVCYNjGftCCVmlBFqNKIGNgUa7MLP3DMe5cuG78sUVZSeHk/AdczLx6USQNJBopdkk9+y+Ya5ppkoFNmjepbJkWrBFTlmBDG3hG4laxIBiKKJUn3lAonfP9KL0uSgx2bq7mHsu4pTBR6Wi+w7klrTeFgrIzlgLqK7kMQ24E1c/ptPFv/CuEyG0XGfYm1Ep2PdlXa+2N+KrVe7Qvdb8gaMIrI4861jnTbSbMH7I0dQJMHOQhLr5EohYMrBgcgf1ZFlo2RUU0Dw7vGONqM/5uGBp49iDpjEINNyEgFTkchwHmY1dRXeFw21jX67z9KD43PW5sjsDFXEbDO3miigpWFL+qDvRstk3daPJ/nmjWOj4S4UpsgvuO8B/MIOnLS49J/Pixi2XZgrIOWnDYcL5kNJqpdIfrI+p01aGEL7JWmNgF/3ea3StNrG/sxKk6KRV9wSrCOla8BdVCzUtmnpmAKhSydhcSqSIzGtuoRgbl/jy1yh4lTZduMcTjzD4TKlJd4QYXrAV4KlvLtTSyYui2NWHIWw4enX3hv/IAFjqQm1EAEvdZlSI=',
        'auth0': 's%3Av1.gadzZXNzaW9ug6ZoYW5kbGXEQJelPy_dcSZ1jt1tTn13JjQcROlK1JOGVV2G05goCavAaNXiuZUi0zZ2oraYqFvuqXB1NJZ-ncXLhhnRHh88dUqmY29va2llg6dleHBpcmVz1_9uJj4AaXrJjq5vcmlnaW5hbE1heEFnZc4PcxQAqHNhbWVTaXRlpG5vbmWkc2JpZJLZIHJDMW9jYzlQeUc5YllvZTF4SllKS1dIWjF5Vnp5VnZX2SBRbkZFdk1GZEt5bUxPU2poOXVLU2w5Yl9mTEVsQzZ1bw.tXEcqRpEfzkhnp9%2FnUs179kAr3DTT%2Bgpgp0mlOub8MI',
        'auth0_compat': 's%3Av1.gadzZXNzaW9ug6ZoYW5kbGXEQJelPy_dcSZ1jt1tTn13JjQcROlK1JOGVV2G05goCavAaNXiuZUi0zZ2oraYqFvuqXB1NJZ-ncXLhhnRHh88dUqmY29va2llg6dleHBpcmVz1_9uJj4AaXrJjq5vcmlnaW5hbE1heEFnZc4PcxQAqHNhbWVTaXRlpG5vbmWkc2JpZJLZIHJDMW9jYzlQeUc5YllvZTF4SllKS1dIWjF5Vnp5VnZX2SBRbkZFdk1GZEt5bUxPU2poOXVLU2w5Yl9mTEVsQzZ1bw.tXEcqRpEfzkhnp9%2FnUs179kAr3DTT%2Bgpgp0mlOub8MI',
    }

    headers = {
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://accounts.britishairways.com',
        'pragma': 'no-cache',
        'priority': 'u=0, i',
        'referer': 'https://accounts.britishairways.com/u/login?state=hKFo2SBULVBLdGZjUER3eEZDcmlWTHhBblA3OC1xNjJxczdCN6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIEl3V01QeGxTMjN3bmRDWmszUmJmUVlFSjBLZ1RYYjhpo2NpZNkgQzhqUnQ2M3BLWGhCWEk5V2dTVVEzdGk5eEFOa0Z0cGg',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'document',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-site': 'same-origin',
        'sec-fetch-user': '?1',
        'upgrade-insecure-requests': '1',
        'user-agent': result.get('ua')
    }
    token = result.get('token')
    params = {
        'state': 'hKFo2SBULVBLdGZjUER3eEZDcmlWTHhBblA3OC1xNjJxczdCN6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIEl3V01QeGxTMjN3bmRDWmszUmJmUVlFSjBLZ1RYYjhpo2NpZNkgQzhqUnQ2M3BLWGhCWEk5V2dTVVEzdGk5eEFOa0Z0cGg',
    }

    data = {
        'state': 'hKFo2SBULVBLdGZjUER3eEZDcmlWTHhBblA3OC1xNjJxczdCN6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIEl3V01QeGxTMjN3bmRDWmszUmJmUVlFSjBLZ1RYYjhpo2NpZNkgQzhqUnQ2M3BLWGhCWEk5V2dTVVEzdGk5eEFOa0Z0cGg',
        'username': 'sadasjkdsa@gmail.com',
        'password': 'asdsadsadas',
        'g-recaptcha-response': token,
        'h-captcha-response': token,
        'captcha': token,
    }
    from primp import Client
    client = Client(proxy=PROXY, impersonate='chrome_133')
    response = client.post('https://accounts.britishairways.com/u/login', params=params, cookies=cookies, headers=headers, data=data)
    print(response.status_code)
    with open('./output.txt', 'w') as f:
        f.write(response.text)