# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, random

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "Your Token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = "http://username:password@host:port"  # Must be HongKong proxy

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    payload = {
        "task_type": "hcaptcha",
        "proxy": PROXY,
        "target_url": "https://accounts.evernote.com/login-with-password",
        "site_key": "9236f198-f154-4aa9-8f4d-2e7ce9aedb5b"
    }
    results = run_task(payload)

    cookies = {
        '_gcl_au': '1.1.1199298898.1765952100',
        '_ga': 'GA1.1.1141496635.1765952101',
        'evernote-openid': '7bb151b34612341566761fbab031a22ec82bb78ccd0aef082e31298a4725f18d.CX008keOhxnhLwXlQOq6HiSqRZBd5hzpb6ZxRhc7cZ4',
        '_ga_3EXC9WZ9CH': 'GS2.1.s1765952100$o1$g0$t1765952113$j57$l0$h0',
        'evernote-local-storage-id': '469a87fe-628c-496d-9ee3-6f7c63bbf0d4',
        'g_state': '{"i_l":0,"i_ll":1765952115946,"i_b":"Zr23CpSg1Dy/bsuKAj6FsvmQfgQ1Q3vOZ1G0ZeLEhQk","i_e":{"enable_itp_optimization":0}}',
    }

    headers = {
        'accept': '*/*',
        'accept-language': 'en,zh-CN;q=0.9,zh;q=0.8',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://accounts.evernote.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://accounts.evernote.com/login-with-password',
        'sec-ch-ua': '"Google Chrome";v="142", "Chromium";v="142", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': results['ua'],
        'x-evernote-anti-csrf': '.',
    }

    data = {
        'email': 'Test123456@gmail.com',
        'password': 'sssssssadjhj1',
        'hCaptchaResponse': results["token"],
        'language': 'en',
    }
    proxies = {
        'https': PROXY
    }
    from primp import Client
    client = Client(proxy=PROXY, impersonate='chrome_133')
    response = client.post('https://accounts.evernote.com/api/checkPassword', cookies=cookies, headers=headers, data=data)
    print(response.text)