import requests
# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, random
from json import dumps as json_dumps
import base64
from urllib.parse import urlencode

BASE_URL = "https://riskbypass.com"  # API base URL
PROXY = f'http://username:password@host:port' # Must be HongKong Proxy
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return
        
def tls_forward(url, method="GET", headers={}, json={}, data='', cookies={}, proxy=None, timeout=30, proxies={}):
    use_proxy = proxies.get('all') or proxies.get('https') or proxy
    if json:
        data = json_dumps(json, separators=(', ', ':'), ensure_ascii=False)
    if type(data) == str:
        body_base64 = base64.b64encode(data.encode()).decode()
    elif type(data) == bytes:
        body_base64 = base64.b64encode(data).decode()
    elif type(data) == dict:
        network_data = urlencode(data)
        body_base64 = base64.b64encode(network_data.encode()).decode()
    else:
        body_base64 = None
    payload = {
        "task_type": "tls_forward",
        "proxy": use_proxy,
        "url": url,
        "method": method,
        "headers": headers,
        "body_base64": body_base64,
        "cookies_dict": cookies,
        "timeout": timeout
    }
    if headers.get('user-agent'):
        payload['user_agent'] = headers.get('user-agent')
    result = run_task(payload)
    if not result:
        raise Exception('TLS Forward Error')
    else:
        return MyResponse(result)

def tls_get(url, headers={}, json={}, data='', cookies={}, proxy=None, timeout=30, proxies={}, params={}):
    if isinstance(params, dict):
        urlparams = urlencode(params)
        url += '?' + urlparams
    return tls_forward(url, 'GET', headers, json, data, cookies, proxy, timeout, proxies)


def tls_post(url, headers={}, json={}, data='', cookies={}, proxy=None, timeout=30, proxies={}, params={}):
    if isinstance(params, dict):
        urlparams = urlencode(params)
        url += '?' + urlparams
    return tls_forward(url, 'POST', headers, json, data, cookies, proxy, timeout, proxies)

class MyResponse:
    def __init__(self, response_dict):
        # 将字典转换为响应对象
        self.body = base64.b64decode(response_dict.get('body_base64').encode())
        self.content = self.body
        self.cookies = response_dict.get('cookies', {})
        self.elapsed = response_dict.get('elapsed', 0)
        self.error = response_dict.get('error', None)
        self.headers = response_dict.get('headers', {})
        self.ok = response_dict.get('ok', False)
        self.reason = response_dict.get('reason', '')
        self.status_code = response_dict.get('status_code', 0)
        self.text = response_dict.get('text', '')
        self.url = response_dict.get('url', '')
    
    def json(self):
        return json.loads(self.body)

if __name__ == "__main__":
    # Task JSON payload
    payload = {
        "task_type": "hcaptcha",
        "proxy": PROXY,
        "target_url": "https://wolt.com/",
        "site_key": "85fed6af-162f-4a66-a7ab-8822a7d81f72",
    }
    result = run_task(payload)
    token = result.get('token')
    cookies = {}

    headers = {
        'accept': 'application/json, text/plain, */*',
        'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
        'app-currency-format': 'wqQxLDIzNC41Ng==',
        'app-language': 'en',
        'cache-control': 'no-cache',
        'client-version': '1.16.67',
        'clientversionnumber': '1.16.67',
        'content-type': 'application/json',
        'h-captcha-response': token,
        'origin': 'https://wolt.com',
        'platform': 'Web',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://wolt.com/',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': result.get('ua'),
    }

    json_data = {
        'attribution': 'GA1.1.1134989426.1767144678:da9c25c4-9425-41f5-9e60-a3ef116044c5:',
        'email': 'asdagvs@gmia.com',
        'audience': 'wolt-com',
        'ref': '/en/discovery',
    }
    
    response = tls_post(url='https://authentication.wolt.com/v3/users/email_login', cookies=cookies, headers=headers, json=json_data,
        proxies={'https':PROXY})

    print(response.text)
