# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install riskbypass
import json, random
from riskbypass import RiskByPassClient

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 120                         # Max task execution time (seconds), exceeding this will throw an exception
PROXY = f"http://xxxxxxxxxxxxx__cr.it:xxxxxxxxxx@gw.dataimpulse.com:{random.randint(10000, 20000)}"

# Task JSON payload
payload = {
  "task_type": "recaptchav3",
  "proxy": PROXY,
  "target_url": "https://vetrina.giocodellotto.it/msite/contents/index.html",
  "site_key": "6Lel_wgsAAAAAFml-Cd6owVOKmxzVW7qYUFH_GPp",
  "title": "lol-mobile",
  "enterprise": False,
  "action": "submit"
}
# Initialize client
client = RiskByPassClient(token=TOKEN, base_url=BASE_URL)
result = client.run_task(payload, timeout=TIMEOUT)

print(json.dumps(result, indent=2))
token = result["token"]
ua = result["ua"]
headers = {
    'sec-ch-ua-platform': '"iOS"',
    'Referer': 'https://vetrina.giocodellotto.it/msite/contents/index.html',
    'sec-ch-ua': '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
    'sec-ch-ua-mobile': '?1',
    'G-Token': token,
    'User-Agent': ua,
    'Accept': 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
}

json_data = {
    'username': 'Davidega17',
    'password': 'mksdnsadns',
    'idRivenditore': 'LI0162',
    'registerGameAccount': False,
    'clientID': 1,
    'platforms': [
        'plat_1',
    ],
}
from curl_cffi import requests
response = requests.post('https://lottoaccount.goldbet.it/multilogin', headers=headers, json=json_data, proxy=PROXY)
print(response.text)