# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, re

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "Your Token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = 'http://username:password@ip:port'

def run_task(payload):
    # Task JSON payload
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    payload =     payload = {
        "task_type": "recaptchav3",
        "proxy": PROXY,
        "target_url": "https://accounts.spotify.com/en/login",
        "site_key": "6LfCVLAUAAAAALFwwRnnCJ12DalriUGbj8FW_J39",
        "title": "Spotify",
        "action": "accounts/login",
        "enterprise": True
    }
    results = run_task(payload)
    
    import primp
    client = primp.Client(proxy=PROXY)
    headers = {
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'accept-language': 'en,zh-CN;q=0.9,zh;q=0.8',
        'cache-control': 'no-cache',
        'pragma': 'no-cache',
        'priority': 'u=0, i',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'document',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-site': 'same-origin',
        'sec-fetch-user': '?1',
        'upgrade-insecure-requests': '1',
        'user-agent': results['ua'],
    }

    response = requests.get('https://accounts.spotify.com/en/login', headers=headers)
    cookies = dict(response.cookies)
    flow_id = re.findall(r'"flowId":"(.*?)"', response.text)[0]
    headers['x-csrf-token'] = response.cookies.get('sp_sso_csrf_token')

    data = {
        'username': 'test123@gmail.com',
        'password': '',
        'remember': 'true',
        'automationKey': '',
        'recaptchaToken': results['token'],
        'continue': f'/en/status?flow_ctx={flow_id}%3A1765986716',
        'flowCtx': flow_id,
        'client_id': '',
    }

    response = client.post('https://accounts.spotify.com/login/otc/start', cookies=cookies, headers=headers, data=data)
    print(response.text)
    print(response.status_code)