# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install riskbypass
import json
from loguru import logger
import time
from riskbypass import RiskByPassClient
from curl_cffi import requests as curl_requests

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 120                         # Max task execution time (seconds), exceeding this will throw an exception
PROXY = "http://xxxxxxxxx_cr.eg:xxxxxxxxxxxxxxxx@gw.dataimpulse.com:10023"

# Số luồng có thể tùy chỉnh ở đây / Number of threads you can adjust
NUM_THREADS = 1


def run_akamai_task(proxy_url):
    task_payload = json.loads(r"""
{
  "task_type": "akamai",
  "proxy": "__PROXY__",
  "target_url": "https://connect.lcwaikiki.com/",
  "akamai_js_url": "https://connect.lcwaikiki.com/nhPK6x5v4/IsxPGpG1/pjT03CNZ/ms/Ya9rfmzQfkfGt69DE3/d2tkKgcmAQ/A0xrAy/woGXsB",
  "page_fp": "424543475255404d424a435b5f465355415a"
}
""".replace("__PROXY__", proxy_url)) # akamai_js_url changed everyday, get it from html <script> tag by xpath or regex when first run.

    client = RiskByPassClient(token=TOKEN, base_url=BASE_URL)
    task_result = client.run_task(task_payload, timeout=TIMEOUT)
    return task_result

def solve_sec_cpt(challenge_data, sec_cpt_cookie=""):
    """
    Giải thử thách sec_cpt (428) bằng RiskByPass
    """
    payload = {
        "task_type": "sec_cpt",
        "sec_json": {
            "nonce": challenge_data.get("nonce"),
            "difficulty": challenge_data.get("difficulty"),
            "token": challenge_data.get("token"),
            "count": challenge_data.get("count"),
            "timestamp": challenge_data.get("timestamp")
        }
    }
    if sec_cpt_cookie:
        payload["sec_cpt"] = sec_cpt_cookie
    else:
        raise Exception('must has sec_cpt_cookie')
    try:
        client = RiskByPassClient(token=TOKEN, base_url=BASE_URL)
        task_result = client.run_task(payload, timeout=TIMEOUT)
        return task_result
    except Exception as e:
        logger.error(f"Lỗi khi chạy RiskByPass sec_cpt: {e}")
        return None

def process_phone(phone_line):
    phone_line = phone_line.strip()
    if not phone_line:
        return
    
    # Ensure phone number starts with +
    phone_num = phone_line if phone_line.startswith('+') else f"+{phone_line}"

    # --- Akamai (First) ---
    akamai_cookies = {}
    akamai_ua = None
    res_akamai = run_akamai_task(PROXY)
    if not res_akamai:
        logger.warning(f"[{phone_num}] Akamai task failed, sẽ thử tiếp.")
    else:
        logger.info(f"[{phone_num}] Akamai task completed, đang trích xuất cookies và UA...")
        akamai_cookies = res_akamai.get("cookies_dict", {})
        akamai_ua = res_akamai.get("ua")
        logger.info(f"[{phone_num}] Akamai cookies: {akamai_cookies}, UA: {akamai_ua}")

    url = "https://connectapi.lcwaikiki.com/lcwconnectbff/service/api/v1/customer/startotp"

    # Setup UA and sec-ch-ua
    final_ua = akamai_ua if akamai_ua else "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36"
    
    # Determine version
    ua_version = "146" if "146.0" in final_ua else "145"

    # Default sec-ch-ua to Chrome
    sec_ch_ua = f"\"Not:A-Brand\";v=\"99\", \"Google Chrome\";v=\"{ua_version}\", \"Chromium\";v=\"{ua_version}\""
    
    # If UA is Edge
    if "Edg/" in final_ua:
         sec_ch_ua = f"\"Not:A-Brand\";v=\"99\", \"Microsoft Edge\";v=\"{ua_version}\", \"Chromium\";v=\"{ua_version}\""

    payload = {
        "phone": phone_num,
        "countryCode": "KE",
        "languageCode": "en"
    }

    headers = {
        'User-Agent': final_ua,
        'Accept': "application/json",
        'Content-Type': "application/json",
        'accept-language': "en-US,en;q=0.9",
        'cache-control': "no-cache",
        'origin': "https://connect.lcwaikiki.com",
        'pragma': "no-cache",
        'priority': "u=1, i",
        'referer': "https://connect.lcwaikiki.com/",
        'sec-ch-ua': sec_ch_ua,
        'sec-ch-ua-mobile': "?0",
        'sec-ch-ua-platform': "\"Windows\"",
        'sec-fetch-dest': "empty",
        'sec-fetch-mode': "cors",
        'sec-fetch-site': "same-site",
        # 'x-user-ip': proxy_ip
    }

    session = curl_requests.Session(impersonate="chrome136")
    if akamai_cookies:
        session.cookies.update(akamai_cookies)
        
    session.proxies.update({
        "http": PROXY,
        "https": PROXY
    })
    session.headers.update(headers)

    max_retries = 3
    for attempt in range(max_retries):
        try:
            logger.info(f"[{phone_num}] Gửi Request (Lần {attempt+1})...")
            response = session.post(url, json=payload, timeout=60)
            
            # Nếu thành công 200 luôn thì dừng
            if response.status_code == 200:
                logger.info(f"[{phone_num}] Kết quả: {response.status_code} - {response.text}")
                return

            resp_json = {}
            try:
                resp_json = response.json()
            except:
                pass
            
            # Kiểm tra Challenge 428
            if response.status_code == 428:
                max_retry_time = resp_json.get('difficulty')//1000
                retry_time = 0
                while resp_json.get("sec-cp-challenge") == "true" or resp_json.get("verify_url"):
                    if retry_time > max_retry_time:
                        raise Exception('sec_cpt bypass error')
                    retry_time += 1
                    logger.warning(f"[{phone_num}] Bị chặn Challenge (Lần {attempt+1}). Đang giải sec_cpt...")
                    
                    sec_cpt_cookie = session.cookies.get("sec_cpt", "")
                    task_result = solve_sec_cpt(resp_json, sec_cpt_cookie)
                    
                    if task_result:
                        # Parse solution
                        solution = task_result.get("solution") if isinstance(task_result, dict) else task_result
                        answers = []
                        if isinstance(solution, list):
                            answers = solution
                        elif isinstance(solution, dict) and "answers" in solution:
                            answers = solution["answers"]
                        else:
                            answers = [solution] if solution else []

                        verify_url = resp_json.get('verify_url')
                        if verify_url and answers:
                            time.sleep(1) # must sleep
                            verify_payload = {
                                "token": resp_json.get("token"),
                                "answers": answers
                            }
                            
                            logger.info(f"[{phone_num}] Verify đang gửi: {verify_payload}")
                            verify_response = session.post(verify_url, json=verify_payload, timeout=60)
                            resp_json = verify_response.json()
                    logger.info(resp_json)
                    time.sleep(1) # must sleep
                    response = session.get('https://connectapi.lcwaikiki.com/_sec/cp_challenge/verify') # must send this
                    resp_json = response.json()
            else:
                # Các lỗi khác (400, 403, 500...)
                logger.error(f"[{phone_num}] Kết quả lỗi: {response.status_code} - {response.text}")
                break

        except Exception as e:
            logger.error(f"[{phone_num}] Lỗi Exception trong vòng lặp: {e}")
            break

def main():
    process_phone("254774589760")

if __name__ == "__main__":
    main()