# -*- coding: utf-8 -*-
# Auto-generated by the RiskByPass panel
# Dependency: pip install requests primp
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"  # API endpoint
TOKEN    = "your token"    # access token (sent as x-api-key)
TIMEOUT  = 60                         # timeout (seconds)
PROXY = "http://user:pwd@host:port"

APIKEY        = "4_PlmTwFRPUWmTpGqjm31WOQ"  # Gigya (SAP CDC) API key
# webSdkBootstrap primes the Gigya cookies (gmid/ucid/hasGmid) before the protected call
BOOTSTRAP_URL = "https://id.pokemoncenter-online.com/accounts.webSdkBootstrap?apiKey=4_PlmTwFRPUWmTpGqjm31WOQ&pageURL=https%3A%2F%2Fwww.pokemoncenter-online.com%2F&sdk=js_latest&sdkBuild=2135&format=json"
LOGIN_URL     = "https://id.pokemoncenter-online.com/accounts.login"

def run_task():
    # task JSON
    payload = {
        "task_type": "shape",
        "proxy": PROXY,
        "site": "pokemon",
        "action": "login"
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task...")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)

    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timed out")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("Status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("Success, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("Task failed:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("Task not found: task_id may be invalid or recycled")
            return
        else:
            print("Unknown response:", j)
            return

def pokemon_test_login():
    from primp import Client

    # one client with a shared cookie jar for the priming GET and the login POST
    c_requests = Client(proxy=PROXY, impersonate='chrome_133', cookie_store=True)

    # prime Gigya cookies (gmid/ucid/hasGmid) with the webSdkBootstrap GET before the protected call
    prime_headers = {
        'accept': '*/*',
        'accept-language': 'zh-CN,zh;q=0.9',
        'origin': 'https://www.pokemoncenter-online.com',
        'referer': 'https://www.pokemoncenter-online.com/',
        'sec-ch-ua': '"Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36',
    }
    boot = c_requests.get(BOOTSTRAP_URL, headers=prime_headers)
    print("Bootstrap GET status:", boot.status_code)

    resp_headers = run_task()
    print(resp_headers)

    # shape headers live in the result's 'headers' sub-dict (keys KsL6nWTYBY-*); UA/sec-ch-ua are not returned, use defaults
    sh = resp_headers.get('headers') or resp_headers

    # shape session cookie (hoPvmDpa) returned by the solver; overrides the bootstrap one, merge into the jar
    ck_str = resp_headers.get('Cookie') or resp_headers.get('cookies')

    ck_dict = {}
    for ck in ck_str.split(';'):
        k, v = ck.strip().split('=', maxsplit=1)
        ck_dict[k] = v

    c_requests.set_cookies(LOGIN_URL, ck_dict)  # merge into the primed jar

    headers = {
        'accept': '*/*',
        'accept-language': 'zh-CN,zh;q=0.9',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://www.pokemoncenter-online.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.pokemoncenter-online.com/',
        'sec-ch-ua': '"Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',  # id.* vs www.* is cross-subdomain
        'user-agent': sh.get('User-Agent') or 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36',
        'ksl6nwtyby-a': sh.get('ksl6nwtyby-a') or sh.get('KsL6nWTYBY-a'),
        'ksl6nwtyby-b': sh.get('ksl6nwtyby-b') or sh.get('KsL6nWTYBY-b'),
        'ksl6nwtyby-c': sh.get('ksl6nwtyby-c') or sh.get('KsL6nWTYBY-c'),
        'ksl6nwtyby-d': sh.get('ksl6nwtyby-d') or sh.get('KsL6nWTYBY-d'),
        'ksl6nwtyby-f': sh.get('ksl6nwtyby-f') or sh.get('KsL6nWTYBY-f'),
        'ksl6nwtyby-z': sh.get('ksl6nwtyby-z') or sh.get('KsL6nWTYBY-z'),
    }

    # form body; captchaToken/captchaType left out on purpose to probe the shape layer alone
    data = {
        'loginID': 'asdasdasd@asd.com',
        'password': 'asdasdasdWSDAw22',
        'sessionExpiration': '3600',
        'targetEnv': 'jssdk',
        'include': 'profile,data',
        'includeUserInfo': 'true',
        'lang': 'ja',
        'APIKey': APIKEY,
        'sdk': 'js_latest',
        'authMode': 'cookie',
        'pageURL': 'https://www.pokemoncenter-online.com/login/',
        'sdkBuild': '2135',
        'format': 'json',
    }

    # cookies ride along automatically from the jar (bootstrap gmid/ucid + solver hoPvmDpa)
    response = c_requests.post(
        LOGIN_URL,
        headers=headers,
        data=data,
    )

    print(response.text)
    print(response.status_code)

    # shape check: this exact errorDetails means the bot-defense layer was cleared (only captchaToken is missing)
    try:
        detail = response.json().get("errorDetails", "")
    except Exception:
        detail = ""
    if "Invalid CaptchaType\nInvalid CaptchaType\nInvalid CaptchaToken" in detail:
        print("Shape passed: reached captcha validation, only captchaToken is missing")

if __name__ == "__main__":
    pokemon_test_login()
