# -*- coding: utf-8 -*-
# Auto-generated by the RiskByPass panel
# Dependency: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"  # API endpoint
TOKEN    = "Your Token"    # access token (sent as x-api-key)
TIMEOUT  = 60                         # timeout (seconds)
PROXY = "http://username:password@ip:port"

def run_task():
    # task JSON
    payload = {
        "task_type": "shape",
        "proxy": PROXY,
        "site": "starbucks",
        "action": "signin"
    }

    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task...")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)

    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timed out")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("Status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("Success, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("Task failed:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("Task not found: task_id may be invalid or recycled")
            return
        else:
            print("Unknown response:", j)
            return

def starbucks_test_signin():
    from primp import Client

    resp_headers = run_task()
    print(resp_headers)

    # shape headers live in the result's 'headers' sub-dict (keys X-DQ7Hy5L1-*); UA/sec-ch-ua are not returned, use defaults
    sh = resp_headers.get('headers') or resp_headers

    cookies = {
        'notice_behavior': 'implied,us',
        'notice_gdpr_prefs': '0,1,2:',
        'cmapi_cookie_privacy': 'permit 1,2,3',
        '_bcnctkn': 'ae254888477d141a2a0dcc12a0ef9820db55',
    }

    headers = {
        'accept': 'application/json',
        'accept-language': 'en-US,en;q=0.9',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'origin': 'https://www.starbucks.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.starbucks.com/account/signin?ReturnUrl=%2F',
        'sec-ch-ua': '"Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': sh.get('User-Agent') or 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36',
        'x-dq7hy5l1-a': sh.get('x-dq7hy5l1-a') or sh.get('X-DQ7Hy5L1-a'),
        'x-dq7hy5l1-b': sh.get('x-dq7hy5l1-b') or sh.get('X-DQ7Hy5L1-b'),
        'x-dq7hy5l1-c': sh.get('x-dq7hy5l1-c') or sh.get('X-DQ7Hy5L1-c'),
        'x-dq7hy5l1-d': sh.get('x-dq7hy5l1-d') or sh.get('X-DQ7Hy5L1-d'),
        'x-dq7hy5l1-f': sh.get('x-dq7hy5l1-f') or sh.get('X-DQ7Hy5L1-f'),
        'x-dq7hy5l1-z': sh.get('x-dq7hy5l1-z') or sh.get('X-DQ7Hy5L1-z'),
    }

    ck_str = resp_headers.get('Cookie') or resp_headers.get('cookies')

    ck_dict = {}
    for ck in ck_str.split(';'):
        k, v = ck.strip().split('=', maxsplit=1)
        ck_dict[k] = v

    cookies.update(ck_dict)

    data = {
        'username': 'asdasdasd@asd.com',
        'password': 'sadasdasdas',
        'rememberMe': True,
        'market': 'US',
        'transactionSubType': 'signin',
        'reputation': {
            'ccAgentName': 'WebApp',
            'platform': 'Web',
            'market': 'US',
            'ubaId': cookies.get('_bcnctkn'),
        },
    }

    c_requests = Client(proxy=PROXY, impersonate='chrome_148')

    response = c_requests.post(
        'https://www.starbucks.com/apiproxy/v1/account/signin',
        cookies=cookies,
        headers=headers,
        json=data,
    )

    print(response.text)
    print(response.status_code)

if __name__ == "__main__":
    starbucks_test_signin()
