import requests_go as requests
# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import time, json, random
import base64
from urllib.parse import urlencode

BASE_URL = "http://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = "http://username:password@host:port"


def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

def riskbypass_tls_forward(url, method, headers, data, cookies, proxy, timeout=30):
    if type(data) == str:
        body_base64 = base64.b64encode(data.encode()).decode()
    elif type(data) == bytes:
        body_base64 = base64.b64encode(data).decode()
    elif type(data) == dict:
        network_data = urlencode(data)
        body_base64 = base64.b64encode(network_data.encode()).decode()
    else:
        body_base64 = None
    payload = {
        "task_type": "tls_forward",
        "proxy": proxy,
        "url": url,
        "method": method,
        "headers": headers,
        "body_base64": body_base64,
        "cookies_dict": cookies,
        "timeout": timeout
    }
    result = run_task(payload)
    if not result:
        raise Exception('TLS Forward Error')
    else:
        return RiskbypassResponse(result)
    

class RiskbypassResponse:
    def __init__(self, response_dict):
        # 将字典转换为响应对象
        self.body = base64.b64decode(response_dict.get('body_base64').encode())
        self.cookies = response_dict.get('cookies', {})
        self.elapsed = response_dict.get('elapsed', 0)
        self.error = response_dict.get('error', None)
        self.headers = response_dict.get('headers', {})
        self.ok = response_dict.get('ok', False)
        self.reason = response_dict.get('reason', '')
        self.status_code = response_dict.get('status_code', 0)
        self.text = response_dict.get('text', '')
        self.url = response_dict.get('url', '')
    
    def json(self):
        return json.loads(self.body)

if __name__ == "__main__":
    cf_payload = {
        "task_type": "cloudflare_waf",
        "proxy": PROXY,
        "target_url": "https://www.fastpeoplesearch.com/kathryn-hebda_id_G-1226652931210924995",
        "target_method": "GET"
    }
    result = run_task(cf_payload)
    cookies = result.get('cookies')
    dd_payload = {
        "task_type": "datadome-slider",
        "proxy": PROXY,
        "target_url": 'https://www.fastpeoplesearch.com/kathryn-hebda_id_G-1226652931210924995',
        "target_method": "POST", 
        "init_cookies": cookies
    }
    result = run_task(dd_payload)
    cookies.update({
        'datadome': result['datadome']
    })
    response = riskbypass_tls_forward(
        url='https://www.fastpeoplesearch.com/kathryn-hebda_id_G-1226652931210924995',
        method='GET',
        cookies=cookies, 
        headers={},
        data='',
        proxy=PROXY
    )
    print(response.text)
    print(response.status_code)
    with open('resp.html', 'w', encoding='utf8') as f:
        f.write(response.text)
