from curl_cffi import requests as c_requests
# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"                     # API base URL
TOKEN    = "Your Token"                                 # Access token (sent as x-api-key)
TIMEOUT  = 60                                           # Timeout (seconds)
PROXY    = "http://username:password@host:port"         # Proxy string

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    # Task JSON payload
    invisibale_payload = {
        "task_type": "datadome-invisible",
        "proxy": PROXY,
        "target_url": "https://100054.connect.garena.com/universal/oauth?redirect_uri=gop100054%3A%2F%2Fauth%2F&response_type=code&client_id=100054&login_scenario=normal&locale=vi_VN",
        "datadome_js_url": "https://datadome.garena.com/tags.js",
        "ddjskey": "AE3F04AD3F0D3A462481A337485081",
        "ddoptions": "{\"ajaxListenerPath\": true, \"allowHtmlContentTypeOnCaptcha\": true}"
    }
    result = run_task(invisibale_payload)

    cookies = {
        '_ga_57E30E1PMN': 'GS2.2.s1754904612$o1$g1$t1754904620$j52$l0$h0',
        '_ga': 'GA1.1.1010148271.1754814702',
        '_ga_RRM2SJW688': 'GS2.1.s1760534332$o5$g1$t1760534433$j60$l0$h0',
        '_ga_XB5PSHEQB4': 'GS2.1.s1762416383$o8$g1$t1762416575$j35$l0$h0',
        '_ga_G8QGMJPWWV': 'GS2.1.s1762939322$o26$g1$t1762940384$j60$l0$h0',
        '_ga_1M7M9L6VPX': 'GS2.1.s1764334315$o59$g1$t1764336101$j60$l0$h0',
        'datadome': result['datadome'],
    }

    headers = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'vi,fr-FR;q=0.9,fr;q=0.8,en-US;q=0.7,en;q=0.6,zh-CN;q=0.5,zh;q=0.4',
        'Connection': 'keep-alive',
        'Referer': 'https://sso.garena.com/universal/login?app_id=10100&redirect_uri=https%3A%2F%2Faccount.garena.com%2F&locale=vi-VN',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin',
        'User-Agent': result['ua'],
        'sec-ch-ua': '"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
    }

    params = {
        'app_id': '10100',
        'account': 'asdasd1234',
        'format': 'json',
        'id': '1764336105856',
    }

    response = c_requests.get('https://sso.garena.com/api/prelogin', params=params, cookies=cookies, headers=headers, proxy=PROXY, impersonate='chrome136')
    print(response.text)