# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"                     # API base URL
TOKEN    = "Your Token"                                 # Access token (sent as x-api-key)
TIMEOUT  = 60                                           # Timeout (seconds)
PROXY    = "http://username:password@host:port"         # Proxy string

def run_task():
    # Task JSON payload
    payload = {
        "task_type": "turnstile",
        "proxy": PROXY,
        "target_url": "https://visa.vfsglobal.com/dza/en/aut/login",
        "site_key": "0x4AAAAAABhlz7Ei4byodYjs"
    }
    
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    result = run_task()
    token = result['token']
    ua = result['ua']

    from tls_client import Session
    c_requests = Session(random_tls_extension_order=True)

    cookies = {
        '__cf_bm': 'PHhoALncSJ0v4SB4t8IE8hvlmd8kSgalv4_o71UNM48-1764469946-1.0.1.1-lTEa8LvCgmQqfFMFRwXby_4MR.jELHKkLAHGpOF7gkjk52RGbybwRLj2N7tZayrQDBEv48prc0kZguIWSdauCESK.SPgLd600zuSWHHe8k8',
        '_cfuvid': 'spxJTfrUcwM10oia0CdsPqOph5vvhVPVyov38vk6eTo-1764469946432-0.0.1.1-604800000',
        'dtCookie': '-3$PE51261CD6VAQL6FEE2OOES0D49UHTFC',
        'rxVisitor': '1764469947609DR22S7U7MK82QJ83KEH525RRBI5E6B1L',
        'rxvt': '1764471747611|1764469947611',
        'dtPC': '-3$469947606_966h1vNFPSKHCCCMJMFVQMEMMACMKRKKRJKTUR-0',
        '_sz_3eb770': 'loaded',
        '_sz_c57861': '51b3d4444bc2723407e86a1d0d32b6f41ee61707',
        '_sz_739498': '66f9905d24fca5bf2e6bc4af554ef400',
        '_sz_8fda62': '76219b6d-746e-42bc-be2e-e0166b4954f3-34b6760938ca57bb58fb41ce64276b0c6fe327c1ff7515cb9c3588d06fbb5bc8',
        'OptanonConsent': 'isGpcEnabled=0&datestamp=Sun+Nov+30+2025+10%3A32%3A33+GMT%2B0800+(%E4%B8%AD%E5%9B%BD%E6%A0%87%E5%87%86%E6%97%B6%E9%97%B4)&version=202508.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=3f8be5e5-e19e-45a0-a57e-97275f4fb0a4&interactionCount=0&isAnonUser=1&landingPath=https%3A%2F%2Fvisa.vfsglobal.com%2Fdza%2Fen%2Faut%2Flogin&groups=C0001%3A1%2CC0003%3A1%2CSPD_BG%3A0%2CC0002%3A0%2CC0004%3A0',
        'cf_clearance': 'vcm0favvAzHxJtJPRdlCfSum6UxftDNxPoPCvQGvk2A-1764469981-1.2.1.1-GEMBjxPXCTn6LOqTPaCOJofSlmB1dP5Kbnqxhy.LFKoF6EfWMstI8tw2ZlZ9yPcEXOQlsfyO6pZRUy0PX7s7IJFWzDP3UW2unDWlWq1yTy6h0BlOaFMif7meNWAC_799z.RfcnVqPNyIt9NzmTgGom4dbaV2Snwc5UUgxaAfrQvt9P8s0LmDi.6O8YqceA5I7BcZLKnbUro4PGBj_67Gb0UA3kjoGHJNka26vNaDwjaK7So_CmKwLvPfNfykQxu2',
    }

    headers = {
        'accept': 'application/json, text/plain, */*',
        'accept-language': 'en',
        'cache-control': 'no-cache',
        'clientsource': 'HN+STtSH6yqA/tNhETZy0ooTvhMpgrErZoHH3GdY3Y3i5tgp535K9bAPcYiCadIJB04enWQhz1V+24KXk37FrS9EhhO/rVDBprItL34bdVsyxiuU4g6ARBPu9+jongqBQ7JIgAeRS4LaoNgmxuE4u9K5c24Fq21VLGOjfCdX93xa76wy1qeTxFaSl1SLPFVPkjU2OH6pIE1BAjMZ1bKHIbxNK0eJFFcS8TTnbWDZUD/RGNXBmEnalszzcKYUHBOKoet8AwipALpOB4dbvKqWna2P3VJQR1Vwa/9rjHBMTMp6BLaexk1c1fCHU2vhzRHfhUwTQvAjwMXO1NQ5wipgkQ==',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://visa.vfsglobal.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://visa.vfsglobal.com/',
        'route': 'dza/en/aut',
        'sec-ch-ua': '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': ua
    }

    data =  {
        "username": "a123456789@gmail.com",
        "password": "QvrE6DiFKg3kS0Er9/X6qhJb8mk63HAnFDlwjVeYJZsJUL7ho5Pu1H3iUt1eMdshSlQPSPDAhbjbLQ76WsU2pEaa6v+0rm369Gql7tQlBDUll93DM4AjJp75BuFCYXQk6vdGdBciG7tdSIhWKD24X5AeYsGRXOPM284y44w/I6fhKefxmaE0TFGqNkMhVBg/c4yUKmdu3HecvzG/tbkcQcXwgwwhruXFs2PkUrHw/OXmWw0S6KOaR206ngR96KP9izQ/Pck0Guo+TQ0WlbTK3HG1zrVRanD26N9VC2o0pLWqOGpFWbZkC5OO205KzLKHUyUXi8Pkc/m75V70skD8yQ==",
        "missioncode": "aut",
        "countrycode": "dza",
        "languageCode": "en-US",
        "captcha_version": "cloudflare-v1",
        "captcha_api_key": token
    }

    response = c_requests.post('https://lift-api.vfsglobal.com/user/login', cookies=cookies, headers=headers, data=data, proxy={'https': PROXY})
    print(response.text)