# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, sys

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "Your Token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = "http://username:password@ip:port"

def run_task():
    # Task JSON payload
    payload = {
        "task_type": "turnstile",
        "proxy": PROXY,
        "target_url": "https://vipcoinfaucet.com/",
        "site_key": "0x4AAAAAACGtxo7VhMXCvFRc"
    }
    
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    results = run_task()

    from curl_cffi import requests

    cookies = {
        'ci_session': '7199apouu8e82ce8te1in230mcuj9gi4',
        '_ga': 'GA1.1.1814138029.1766125885',
        '_ga_L6KYQ0805E': 'GS2.1.s1766125885$o1$g0$t1766125897$j48$l0$h0',
    }

    headers = {
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'accept-language': 'en',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
        'origin': 'https://vipcoinfaucet.com',
        'pragma': 'no-cache',
        'priority': 'u=0, i',
        'referer': 'https://vipcoinfaucet.com/',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'document',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-site': 'same-origin',
        'sec-fetch-user': '?1',
        'upgrade-insecure-requests': '1',
        'user-agent': results['ua']
    }

    data = {
        'ci_csrf_token': '',
        'wallet': 'starvictory117@gmail.com',
        'uid': '',
        'private_ip': '',
        'telegram_user_id': '',
        'telegram_first_name': '',
        'telegram_last_name': '',
        'telegram_username': '',
        'telegram_language_code': '',
        'telegram_is_premium': '',
        'telegram_photo_url': '',
        'captcha': 'turnstile',
        'cf-turnstile-response': results['token']
    }

    response = requests.post('https://vipcoinfaucet.com/app/auth/validation', cookies=cookies, headers=headers, data=data)
    print(response.text)
    print(response.url)