# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, random

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "yout token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = f'http://username:password@host:port'


def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    # Task JSON payload
    payload = {
        "task_type": "perimeterx_invisible",
        "proxy": PROXY,
        "target_url": "https://www.avis.com/en/home",
        "perimeterx_js_url": "https://www.avis.com/_static/scripts/init.js",
        "pxAppId": "PXn6KwGY36"
    }
    result = run_task(payload)
    cookies = result.get("cookies")

    headers = {
        'accept': '*/*',
        'accept-language': 'zh-CN,zh;q=0.9',
        'cache-control': 'no-cache',
        'content-type': 'application/json;charset=UTF-8',
        'origin': 'https://www.avis.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://www.avis.com/en/home',
        'sec-ch-ua': '"Not(A:Brand";v="8", "Chromium";v="144", "Google Chrome";v="144"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': result.get('ua'),
        'x-dtpc': '20$112391164_604h59vNROWJCOKUPMNFPBALRPCSUBPLPCKQCSN-0e0',
    }

    params = {
        'aid': 'default_application',
        'clientId': '1IhTGEPCS6jumvCDnGvcm',
        'locale': 'zh-CN',
    }

    json_data = {
        'data': {
            'collection_result': {
                'metadata': {
                    'timestamp': 1770112392545,
                },
                'content': {},
            },
            'policy_request_id': 'dxp_iam_login_v1',
            'params': {
                'request_context': {
                    'correlation_identifier': '3efaf8c8-5ea0-4ff3-9d9a-ab9840013039',
                    'channel_info': {
                        'channel_code': 'DIGITAL_CHANNEL',
                        'domain_country': 'US',
                        'host_name': 'www.avis.com',
                    },
                    'locale': 'en_US',
                    'ip_address': '1.1.1.1',
                    'security_profiling_info': {
                        'name': 'test',
                        'value': 'test',
                    },
                    'device_type': 'web',
                    'application_user_identifier': 'User',
                },
                'credentials': {
                    'username': 'a1796asd932792@gmail.com',
                    'password': 'asdsad213.',
                    'remember_me': False,
                },
                'access_token': None,
            },
        },
        'headers': [
            {
                'type': 'correlation_id',
                'correlation_id': 'c0ee968d-1a4f-4609-a6a9-048133e12fee',
            },
            {
                'type': 'device',
                'device': {
                    'device_key_id': '6a605bfe636e4e3b0921072052b9184ecc0f272c2ce27d06ceaa78ed007a45d3',
                    'device_public_key': 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1BMWUdJO39qkg8iEEZIlCjUVOPyfy2X2HHA/qQ+TyGoVpb/jNSR53gTf/vzLURLwxqqMPDLlnoLRgNUOG1kZmEGHICVHfjM1vjGhr++uCf5TRkuok8jnqqsu6hLpJabagzXOln1bcbQ1FHgUaUhuRgPz/zYh+mdtAQujPlEP/oVA4EqrLb8ruR1Qr1GZRcbaK3ANbHfLCCq0n4s2mmNQcTZ/GfWIxkKh5oFjQsNZgJT7xqsWilgEZ5577+DHmX4vcAkpp5yogjv3TsGKuqvn8pP2Yuo4fr7sHRq1BHQOGXQ2yd66HMkAWJ6kpvG0ISed/o1jvcN21Nu0/bjZe6dPyQIDAQAB',
                    'device_type': 'web',
                    'device_os': 'win32',
                    'device_os_version': '144.0',
                    'device_manufacturer': 'Google Inc.',
                    'device_model': 'Win32',
                },
            },
        ],
    }
    from curl_cffi import requests as c_requests
    response = c_requests.post(
        'https://www.avis.com/ido/api/v2/auth/anonymous_invoke',
        params=params,
        cookies=cookies,
        headers=headers,
        json=json_data,
        proxy=PROXY,
        impersonate='chrome133a'
    )
    print(response.text)