# -*- coding: utf-8 -*-
# Auto-generated by RiskByPass Task Panel
# Deps: pip install requests
import requests, time, json, random

BASE_URL = "https://riskbypass.com"  # API base URL
TOKEN    = "your token"    # Access token (sent as x-api-key)
TIMEOUT  = 60                         # Timeout (seconds)
PROXY = f"http://username:password@host:port"

def run_task(payload):
    session = requests.Session()
    headers = {"Content-Type": "application/json", "x-api-key": TOKEN}

    print("Submitting task…")

    try:
        resp = session.post(f"{BASE_URL}/task/submit", headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print("Submit request error:", repr(e))
        return

    if not data.get("ok"):
        print("Submit failed:", data)
        return

    task_id = data.get("task_id")
    if not task_id:
        print("No task_id in response:", data)
        return

    print("Submitted, task_id =", task_id)
    
    start_time = time.time()

    while True:
        if time.time() - start_time > TIMEOUT:
            print("Timeout (seconds)")
            return
        try:
            r = session.get(f"{BASE_URL}/task/result/{task_id}", headers={"Cache-Control":"no-cache"}, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            print("Polling error:", repr(e))
            time.sleep(1)
            continue

        st = j.get("status", "UNKNOWN")
        print("status:", st)

        if st in ("RUNNING", "QUEUED"):
            time.sleep(1)
            continue

        if st == "SUCCESS":
            print("SUCCESS, result:", json.dumps(j.get("result"), ensure_ascii=False, indent=4))
            return j.get("result")
        elif st == "FAILED":
            print("FAILED:", j.get("error", j))
            return
        elif st == "NOT_FOUND":
            print("NOT_FOUND: maybe invalid or recycled task_id")
            return
        else:
            print("UNKNOWN:", j)
            return

if __name__ == "__main__":
    # Task JSON payload
    cf_payload = {
        "task_type": "cloudflare_waf",
        "proxy": PROXY,
        "target_url": "https://app.prizepicks.com/login",
        "target_method": "GET"
    }
    cf_result = run_task(cf_payload)
    if not cf_result:
        raise Exception('CloudFlare WAF Failed!')
    cookies = cf_result.get("cookies")
    px_payload = {
        "task_type": "perimeterx_invisible",
        "proxy": PROXY,
        "target_url": "https://app.prizepicks.com/login?utm_source=landing&utm_medium=website&_gl=1*1h5g9sc*_gcl_au*MTg2NDQxNzIwNi4xNzY4MTA3NTEw",
        "perimeterx_js_url": "https://app.prizepicks.com/ZNeitfzP/init.js",
        "pxAppId": "PXZNeitfzP"
    }
    px_result = run_task(px_payload)
    if not px_result:
        raise Exception('PerimeterX Invisible Failed')
    cookies.update(px_result.get("cookies"))
    headers = {
        'accept': 'application/json',
        'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'origin': 'https://app.prizepicks.com',
        'pragma': 'no-cache',
        'priority': 'u=1, i',
        'referer': 'https://app.prizepicks.com/',
        'sec-ch-ua': '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
        'x-device-id': 'f9117899-477d-4bc9-9865-bac761044cfc',
        'x-device-info': 'anonymousId=,name=,os=windows,osVersion=Windows NT 10.0; Win64; x64,platform=web,appVersion=,gameMode=prizepools,stateCode=CA,fbp=fb.1.1768107510900.564192758347859369',
    }

    json_data = {
        'user': {
            'email': 'mickewats312+934@gmail.com',
            'password': 'ZDspider05!',
            'remember_me': True,
        },
        'token': '',
    }
    from curl_cffi import requests
    response = requests.post('https://api.prizepicks.com/users/sign_in', cookies=cookies, headers=headers, json=json_data, impersonate='chrome136', proxy=PROXY)
    print(response.text)